### ISSUE TITLE
Add support for multi disk LUNS : Production & Cost concious setup

### ISSUE THREAD

**Issue by shekharsorot** [Azure/sap-automation#102]
**Is your feature request related to a problem? Please describe.**

Certified Azure production HANA currently requires 4x disks based LVM for Data and 3x disks based Log volumes ( with Write accelerator enabled ).
In addition, A cost conscious setup ( Non certified ) setup is typically provisioned in non-production (dev,qa,sbx) environment.
Current jinja template (https://github.com/Azure/sap-automation/blob/main/deploy/ansible/roles-os/1.5-disk-setup/templates/volume_groups.j2:16) can only process by creating LVMs comprising of single disks.

This has a technical limitation as the stripe size set during LVM creation based on number of participating disks and cannot be changed later without a complete rebuild. It also limits performance to 1x the disk irrespective of how many disks you add into the LVM in future.

**Describe the solution you'd like**
Modify the template https://github.com/Azure/sap-automation/blob/main/deploy/ansible/roles-os/1.5-disk-setup/templates/volume_groups.j2:16 code block to below code

{%     for disk in disks if (disk.host == inventory_hostname) and (disk.type == disktype) %}
{%        for lun in disk.LUN%}
{%         set _ = pvlist.append('/dev/disk/azure/scsi1/lun' ~ lun) %}
{%        endfor %}
{%     endfor %}

This will require TF code be  to modified in  how it outputs the sap-automation.yaml file from the templates.

A sample disks block will be as below
# disks:
#   - { host: 'hana-01', luns: [0], type: 'usrsap'}
#   - { host: 'hana-01', luns: [1], type: 'hanashared'}
#   - { host: 'hana-01', luns: [11,12,13,14], type: 'hanadata'}
#   - { host: 'hana-01', luns: [21,22,23], type: 'hanalog'}
#   - { host: 'hana-01', luns: [31], type: 'hanabackup'}

Note the comma separated array / list of iSCSI LUN numbers.

For Cost Conscious HANA setup, we could go for 4x disks combined in a single Volume group, which carves out 3 LVM , one each for Shared, Data and Log. An identifier for this in  vars/disk_config.yaml file can be added to allow 

**Additional context**
Recommendations/requests here are based on official documentation
https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations-storage

**Comment by PankajMeshramCSA** [comment]
@shekharsorot  - I have checked with the team and they haven't seen this as an issue, we create a PV containing all the disks of a specific type. Additionally, the code for creating disks relies on various files including the var/disk_config.yaml.

On the cost conscious configuration - the custom disk sizes yaml can be specified with the configuration required

**Comment by shekharsorot** [comment]
This issue is very old and i see that code has been updated to accommodate custom disk layout.
