### ISSUE TITLE
[BUG] fatal: [localhost]: FAILED! => {"changed": false, "msg": "Authentication error, please check the SAS token"}

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#103]
**Describe the bug**
The Storage Container SAS token doesn't work

**To reproduce**
Setup everything according to documentation and try to download sap binaries.
The error 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Authentication error, please check the SAS token"}
will complain that the SAS token is incorrect.

**Expected behavior**
SAS Token as created and placed in to keyvault during control plane deployment is usable

**Additional context**
The workaround is:
Create the SAS token for the sapbits container manually again and update the secret in the keyvault with a leading "?":
storage account: e.g. mgmtnoeusaplibcde -> container "sapbits"
keyvault: e.g. MGMTNOEUDEP00userEAC 
secret: sapbits-sas-token
set a new value: ?<sas token>

**Comment by sapien47** [comment]
thank you very much, worked for me

**Comment by debi74** [comment]
Hi,

When I ran the command "ansible-playbook ./sap-automation/deploy/ansible/playbook_bom_downloader.yaml......." with the SAS token of storage account (as per the MS document), I encountered two errors :

1. TASK [roles-sap/0.1-bom-validator : 0.1 BoM Validator: - Check storage account container] *******************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["az", "storage", "blob", "upload", "--account-name", "debiacsssto", "--sas-token", "?sv=2021-06-08&ss=bfqt&srt=c&sp=rwdlacupiytfx&se=2023-07-29T19:04:24Z&st=2022-07-29T11:04:24Z&spr=https,http&sig=98qo6q6XUznPhOb78RVGOi9ptIghjw5rxwCXUnuL6K4%3D", "--container-name", "sapbits/sapfiles/archives", "--name", "readme.md", "--file", "/mnt/downloads/readme.md", "--if-none-match", "*", "--no-progress"], "delta": "0:00:00.664886", "end": "2022-07-29 11:05:58.152586", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2022-07-29 11:05:57.487700", "stderr": "ERROR: This request is not authorized to perform this operation using this resource type.\nRequestId:70633cf1-401e-00b0-783b-a34c45000000\nTime:2022-07-29T11:05:58.0084558Z\nErrorCode:AuthorizationResourceTypeMismatch", "stderr_lines": ["ERROR: This request is not authorized to perform this operation using this resource type.", "RequestId:70633cf1-401e-00b0-783b-a34c45000000", "Time:2022-07-29T11:05:58.0084558Z", "ErrorCode:AuthorizationResourceTypeMismatch"], "stdout": "", "stdout_lines": []}
...ignoring


2. TASK [roles-sap/0.1-bom-validator : BOM: S41909SPS03_v0011ms Authentication error SAPCAR_1115-70006178.EXE] *************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Authentication error, please check the SAS token"}

Then, I use the SAS token of sapbits in that command and the first error gone and then I can see the sapfiles/archive folders created under sapbits and also README.md file also present there. But still the second error is coming.

Can you please let me know how to solve this issue?

Thanks
Debi Prasad
