### ISSUE TITLE
[BUG] Control plain deployment fails when installing azure.azcollection

### ISSUE THREAD

**Issue by akrutikov98** [Azure/sap-automation#106]
Script  ${DEPLOYMENT_REPO_PATH}/deploy/scripts/prepare_region.sh terminated with the error below:

module.sap_deployer.null_resource.prepare-deployer[0] (remote-exec): + sudo -H /opt/ansible/venv/2.9/bin/ansible-galaxy collection install azure.azcollection --force --collections-path /opt/ansible/collections
module.sap_deployer.null_resource.prepare-deployer[0] (remote-exec): ERROR! Unexpected Exception, this is probably a bug: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/opt/ansible/venv/2.9/lib/python3.8/site-packages/ansible/utils/collection_loader/__init__.py)

Run script ${DEPLOYMENT_REPO_PATH}/deploy/scripts/prepare_region.sh along with the options as outlined in the documentation.

**Comment by mimergel** [comment]
As a workaround please use the 18.04 image reference in the deployer tfvar file (e.g. MGMT-WEEU-DEP00-INFRASTRUCTURE.tfvars) until the issue has been fixed for 20.04

`
deployer_image={
"os_type" = "Linux"
"source_image_id" =""
"publisher" ="Canonical"
"offer" ="UbuntuServer"
"sku" ="18.04-LTS"
"version" ="latest"
}
`

**Comment by Z9995083** [comment]
Or as second workaround fix the version of ansible-lint to 5..4.0 in configure_deployer.sh.tmpl:
sudo $${ansible_venv_bin}/pip3 install \
    "ansible>=$${ansible_major}.$${ansible_minor},<$${ansible_major}.$((ansible_minor + 1))" \
    **'ansible-lint<5.5'** \
    argcomplete \
    'pywinrm>=0.3.0' \
    yamllint \
    msal

**Comment by KimForss** [comment]
Hi @Z9995083, is this still an issue for you?

//Kimmo
