### ISSUE TITLE
[BUG] HTTP Error 404: The specified resource does not exist.", "status_code": 404, "url": 

### ISSUE THREAD

**Issue by cjpark-sapcsa** [Azure/sap-automation#113]
Hi Team, 

i am in the step of  Playbook: BOM Processing This playbook downloads the SAP software to the SCS virtual machine.

and i face the below error, from BOM processor.  

from the storage account  https://mgmtaueasapliba30.blob.core.windows.net/sapbits/sapfiles/archives/SAPCAR_1115-70006178.EXE  , URL has been correctly generated...

but the BOM processing...  pick up some additional letter after. EXE.      

"https://mgmtaueasapliba30.blob.core.windows.net/sapbits/sapfiles/archives/SAPCAR_1115-70006178.EXEWestBrom1"}

i wonder where i can delete this additional letter  

TASK [roles-sap/3.3-bom-processing : 3.3 BoM Processing: - Download Files suse12] **********************************************************************************
failed: [x00scs00l1e2] (item={'name': 'SAPCAR 7.22; OS: Linux on x86_64 64bit', 'archive': 'SAPCAR_1115-70006178.EXE', 'checksum': '765412436934362cc5497e3d659fbb78be91093a091c11ec4fbe84dfb415a0e5', 'filename': 'SAPCAR', 'permissions': '0755', 'url': 'https://softwaredownloads.sap.com/file/0020000000098642022'}) => {"ansible_loop_var": "item", "attempts": 2, "changed": false, "dest": "/usr/sap/install/downloads/SAPCAR", "elapsed": 0, "item": {"archive": "SAPCAR_1115-70006178.EXE", "checksum": "765412436934362cc5497e3d659fbb78be91093a091c11ec4fbe84dfb415a0e5", "filename": "SAPCAR", "name": "SAPCAR 7.22; OS: Linux on x86_64 64bit", "permissions": "0755", "url": "https://softwaredownloads.sap.com/file/0020000000098642022"}, "msg": "Request failed", "response": "HTTP Error 404: The specified resource does not exist.", "status_code": 404, "url": "https://mgmtaueasapliba30.blob.core.windows.net/sapbits/sapfiles/archives/SAPCAR_1115-70006178.EXEWestBrom1"}
FAILED - RETRYING: 3.3 BoM Processing: - Download Files suse12 (2 retries left).
^C [ERROR]: User interrupted execution

"https://mgmtaueasapliba30.blob.core.windows.net/sapbits/sapfiles/archives/SAPCAR_1115-70006178.EXEWestBrom1}

**Comment by KimForss** [comment]
Hi, you can delete the extra characters, however it would be good to identify why they got there in the first place.

Which BoM is this and which branch are you using?

**Comment by cjpark-sapcsa** [comment]
Good morning

Thanks for your response. I am using S41909SPS03_v0010ms BOM with main Branch.  

Which file i need to open to delete  “extra character ? ? 

B. Rgds



azureadm@mgmtaueadep00deploy00:~$

azureadm@mgmtaueadep00deploy00:~$ ls -d ${DEPLOYMENT_REPO_PATH}/deploy/ansible/BOM-catalog/S41909SPS03* | xargs basename
S41909SPS03_v0010ms


workload zone 

#  Please save these values:                                                            #
#     - Key Vault: MGMTAUEADEP00user45F                                                 #
#     - Deployer IP:                                                       #
#     - Storage Account: mgmtaueatfstatea30            

MGMT-AUEA-SAP_LIBRARY
mgmtaueatfstatea30

MGMT-AUEA-DEP00-INFRASTRUCTURE
MGMTAUEADEP00user45F

**Comment by PankajMeshramCSA** [comment]
@cjpark-sapcsa  - Hi Chan, I see this is quite old request, not sure if you managed to move ahead, we have the whole new DevOps approach. Could you please check and confirm the closure for this one?
