### ISSUE TITLE
install_workloadzone.sh: Error: "network_acls.0.ip_rules.0" is not a valid IPv4 address

### ISSUE THREAD

**Issue by abeletkeman** [Azure/sap-automation#116]
Getting the following error when trying to deploy the workload zone from the deployer VM per the tutorial https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-deploy-workload-zone?tabs=linux

#########################################################################################
#                                                                                       #
#                             Running Terraform plan                                    #
#                                                                                       #
#########################################################################################

Error: "network_acls.0.ip_rules.0" is not a valid IPv4 address: "3f27b93e-3b0a-4871-91fb-fc2695718314"

  with module.sap_landscape.azurerm_key_vault.kv_user[0],
  on ../../terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf line 77, in resource "azurerm_key_vault" "kv_user":
  77:     ip_rules = var.use_private_endpoint ? (
  78:       compact
  79:       (
  80:         [
  81:           length(local.deployer_public_ip_address) > 0 ? local.deployer_public_ip_address : "",
  82:           length(var.Agent_IP) > 0 ? var.Agent_IP : ""
  83:         ]
  84:       )) : (
  85:       []
  86:     )

Error: network_acls.0.ip_rules.0 must start with IPV4 address and/or slash, number of bits (0-32) as prefix. Example: 127.0.0.1/8. Got "3f27b93e-3b0a-4871-91fb-fc2695718314".

  with module.sap_landscape.azurerm_key_vault.kv_user[0],
  on ../../terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf line 77, in resource "azurerm_key_vault" "kv_user":
  77:     ip_rules = var.use_private_endpoint ? (
  78:       compact
  79:       (
  80:         [
  81:           length(local.deployer_public_ip_address) > 0 ? local.deployer_public_ip_address : "",
  82:           length(var.Agent_IP) > 0 ? var.Agent_IP : ""
  83:         ]
  84:       )) : (
  85:       []
  86:     )

#########################################################################################
#                                                                                       #
#                             Errors running plan                                    #
#                                                                                       #
#########################################################################################

Warning: Empty provider configuration blocks are not required

  on ../../terraform-units/modules/sap_landscape/providers.tf line 1:
   1: provider "azurerm" {

Remove the azurerm.main provider block from module.sap_landscape. Add azurerm.main to the list of configuration_aliases for azurerm in
required_providers to define the provider configuration name.

(and 2 more similar warnings elsewhere)

**To reproduce**
1. Create a landscape tfvars file (parameters below, copied from one of the example files)
2. Set environment variables per the tutorial
3. Execute install_workloadzone.sh per the tutorial (link above)

**Expected behavior**
The script should complete without error and create the infrastructure expected.

**Additional context**
Parameters:
tfstate_resource_id  = null
deployer_tfstate_key = null
environment = "SBX"
location = "northcentralus"
network_logical_name = "SAP00"
network_address_space = "10.150.0.0/16"
admin_subnet_address_prefix = "10.150.0.0/19"
db_subnet_address_prefix = "10.150.96.0/19"
app_subnet_address_prefix = "10.150.32.0/19"
web_subnet_address_prefix = "10.150.128.0/19"
/* iscsi subnet information */
automation_username = "azureadm"
enable_purge_control_for_keyvaults = false
NFS_provider          = "AFS"
transport_volume_size = 100
/* anf subnet information */
use_private_endpoint = true

Is this related to bug #77 ?

**Comment by ErickSegaar** [comment]
Running into the same behaviour here. Any update on this?

**Comment by hdamecharla** [comment]
Fixed as part of #168, network_acls added to ignore list of lifecycle changes as part of #319
