### ISSUE TITLE
[BUG] System management is locked by the application with pid from zypper

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#12]
**Describe the bug**
When playbook_02_os_sap_specific_config.yaml runs directly after playbook_01_os_base_config.yaml it always files with this error.
Please add an ansible step to playbook 2 that checks for running zypper or yum and waits until these processes finishes.

**To reproduce**
run the playbooks 1 & 2 directly after each other

**Expected behavior**
no playbook failures due to running zypper or yum

**Additional context**
none

**Comment by PankajMeshramCSA** [comment]
@mimergel - another one :) 

could you please check if this issue still exists? If not, please close this one. Thanks.

**Comment by mimergel** [comment]
the issue has not been observed since a long time. must be solved!
closing. thanks
