### ISSUE TITLE
[Feature] Please provide deployment support for ANF AVG +  manual QoS capacity pool & throughput_in_mibps settings

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#120]
**Feature**
Please provide deployment support for Azure Netapp Files Application Volume Group.
This requires manual QoS capacity pool. therefore settings of throughput_in_mibps will be required as well.

**Solution**
Using the deployment automation framework for ANF and AVG to ensure storage and DB are in close proximity for optimal performance.
https://docs.microsoft.com/en-us/azure/azure-netapp-files/application-volume-group-introduction 

**Alternatives**
Until this feature is available separate terraform scripts and manual mounting is required. 

**Additional context**
Please also add ANF related OS parameters

**Comment by KimForss** [comment]
Fixed in the 3.4 release

**Comment by mimergel** [comment]
@KimForss , can this be opened again as AVG is not yet included?
