### ISSUE TITLE
[BUG] Missing required argument hana_dual_nics

### ISSUE THREAD

**Issue by RSteeno** [Azure/sap-automation#123]
**Describe the bug**
Running a new system deployment via pipeline and ran into the following error:

```
#########################################################################################
#                                                                                       #
#                             Running Terraform plan                                    #
#                                                                                       #
#########################################################################################


Error: Missing required argument

  on module.tf line 34, in module "common_infrastructure":
  34: module "common_infrastructure" {

The argument "hana_dual_nics" is required, but no definition was found.

```

**To reproduce**
1. Execute the ```03-sap-system-deployment.yaml``` pipeline.

**Expected behavior**
For values which are not defined in the sample system tfvars file, this should follow the same pattern of having a default value secified in the variable definition file.

**Additional context**
Variable defined on line 86 in ```deploy\terraform\terraform-units\modules\sap_system\common_infrastructure\variables_local.tf``` should have a default value set.

**Comment by PankajMeshramCSA** [comment]
@RSteeno  - I see this is quite old. We have successful pipelines running now. Could you please confirm ?

**Comment by RSteeno** [comment]
> @RSteeno - I see this is quite old. We have successful pipelines running now. Could you please confirm ?

Yes, this can be closed.

**Comment by PankajMeshramCSA** [comment]
Thanks @RSteeno - Closing this one now.
