### ISSUE TITLE
Please provide the option to install PAS and WebDisp on the SCS VM

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#13]
**Is your feature request related to a problem? Please describe.**
Some customers don't need to have SCS or Webdispatcher and on a separate host.

**Describe the solution you'd like**
Please provide the option to install PAS and WebDisp on the SCS VM. 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by KimForss** [comment]
Work in progress

**Comment by KimForss** [comment]
This is resolved
