### ISSUE TITLE
[BUG] Default value of the variable "db_platform" should be the name of a database platform

### ISSUE THREAD

**Issue by yertaylan67** [Azure/sap-automation#144]
Please check the variable "db_platform" in https://github.com/Azure/sap-automation/blob/main/deploy/terraform/terraform-units/modules/sap_namegenerator/variables_local.tf. Its default value should not be LINUX, but a database platform.

**Comment by PankajMeshramCSA** [comment]
@yertaylan67 - This parameter does not exists anymore, could you please confirm?

**Comment by yertaylan67** [comment]
@PankajMeshramCSA sorry, the variable db_platform is listed in https://github.com/Azure/sap-automation/blob/main/deploy/terraform/terraform-units/modules/sap_namegenerator/variables_global.tf.

**Comment by PankajMeshramCSA** [comment]
@yertaylan67  - I have created a PR to solve this one now - https://github.com/Azure/sap-automation/pull/376
