### ISSUE TITLE
[BUG] Syntax Error on OS SAP Specific Configuration

### ISSUE THREAD

**Issue by barisberkbulut** [Azure/sap-automation#145]
**Describe the bug**
I get the syntax error when i try to run the OS SAP Specific Configuration:

**To reproduce**
~/Azure_SAP_Automated_Deployment/sap-automation/deploy/ansible/configuration_menu.sh

Option 2

3. See error

Read vars_file 'vars/ansible-input-api.yaml'
Read vars_file 'vars/ansible-input-api.yaml'
Read vars_file 'vars/ansible-input-api.yaml'
Read vars_file 'vars/ansible-input-api.yaml'
Read vars_file 'vars/ansible-input-api.yaml'

ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line 1 column 1 (char O)
Syntax Error while loading YAML .
could not find expected ':'

The error appears to be in /home/azureadm/Azure_SAP_Automated_Deployment/sap-automation/deploy/ansible/roles-sap-os/2.6-sap-mounts/tasks/2.6.0-afs-mounts.yaml': line 94, column 15, but may be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:

<<<<<<< HEAD
	               when:			MULTI_SIDS is defined
	                       ^ here

**Additional context**
I also tried inputting variables in the following Ansible to configure page as follows, yet the same error occurred. 

sap_params_file=sap-parameters.yaml

if [[ ! -e "${sap_params_file}" ]]; then
        echo "Error: '${sap_params_file}' file not found!"
        exit 1
fi

"# Extract the sap_sid from the sap_params_file, so that we can determine
"# the inventory file name to use.
sap_sid="$(awk '$1 == "sap_sid:" {print $2}' ${sap_params_file})"

kv_name="$(awk '$1 == "kv_name:" {print $2}' ${sap_params_file})"

prefix="$(awk '$1 == "secret_prefix:" {print $2}' ${sap_params_file})"
password_secret_name=$prefix-sid-password

password_secret=$(az keyvault secret show --vault-name ${kv_name} --name ${password_secret_name} | jq -r .value)

export           ANSIBLE_PASSWORD=$password_secret
export           ANSIBLE_INVENTORY="${sap_sid}_hosts.yaml"
export           ANSIBLE_PRIVATE_KEY_FILE=sshkey
export           ANSIBLE_COLLECTIONS_PATHS=/opt/ansible/collections${ANSIBLE_COLLECTIONS_PATHS:+${ANSIBLE_COLLECTIONS_PATHS}}
export           ANSIBLE_REMOTE_USER=azureadm

"# Ref: https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html
"# Silence warnings about Python interpreter discovery
export           ANSIBLE_PYTHON_INTERPRETER=auto_silent

"# Set of options that will be passed to the ansible-playbook command
playbook_options=(
        --inventory-file="${sap_sid}_hosts.yaml"
        --private-key=${ANSIBLE_PRIVATE_KEY_FILE}
        --extra-vars="_workspace_directory=`pwd`"
        --extra-vars="@${sap_params_file}"
        -e ansible_ssh_pass='{{ lookup("env", "ANSIBLE_PASSWORD") }}'
        "${@}"
)

ansible-playbook "${playbook_options[@]}" ~/Azure_SAP_Automated_Deployment/sap-automation/deploy/ansible/playbook_01_os_base_config.yaml

(the quotes before number signs have put by me to simplify the view.)

**Comment by KimForss** [comment]
merge conflict, is relsolved, sorry for not responding earlier
