### ISSUE TITLE
[BUG] prepare_region.sh failing if Deployer IP is IPv6

### ISSUE THREAD

**Issue by osedlacek** [Azure/sap-automation#158]
Running prepare_region.sh get this error.

Error: "network_acls.0.ip_rules.0" is not a valid IPv4 address: "f8f3db70-239b-4fc6-ad2a-1c386961a5df"

  with module.sap_landscape.azurerm_key_vault.kv_user[0],
  on ../../terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf line 61, in resource "azurerm_key_vault" "kv_user":
  61:     ip_rules = var.use_private_endpoint ? (
  62:       compact
  63:       (
  64:         [
  65:           length(local.deployer_public_ip_address) > 0 ? local.deployer_public_ip_address : "",
  66:           length(var.Agent_IP) > 0 ? var.Agent_IP : ""
  67:         ]
  68:       )) : (
  69:       [
  70:         length(var.Agent_IP) > 0 ? var.Agent_IP : ""
  71:       ]
  72:     )

**Comment by PankajMeshramCSA** [comment]
checked with @osedlacek and he has confirmed to close this one. He is going to run the deployments using WebApp/Pipelines.
