### ISSUE TITLE
[Feature]: Please urgently provide the possibility to deploy a secondary virtual IP as enabler for adaptive compute

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#159]
**Is your feature request related to a problem? Please describe.**
All SAP systems are installed on secondary virtual IPs to allow adaptive compute approach.

**Describe the solution you'd like**
Please add the possibly to deploy a secondary IP address. 

**Describe alternatives you've considered**
For now this is a manual additional step which doesn't make sense and is a show-stopper to use the automation framework.

**Additional context**
https://techcommunity.microsoft.com/t5/running-sap-applications-on-the/use-sap-virtual-host-names-with-linux-in-azure/ba-p/3251593

**Comment by KimForss** [comment]
Fixed in 3.4 release
