### ISSUE TITLE
[BUG] BOM for S41909SPS03_v0008ms has old archives (SAP changed Patchlevel)

### ISSUE THREAD

**Issue by enterprise-1701-d** [Azure/sap-automation#18]
**Describe the bug**
the following error is reported during download of the BOM "S41909SPS03_v0008ms" by using

cd ~/Azure_SAP_Automated_Deployment/WORKSPACES/BOMS
~/Azure_SAP_Automated_Deployment/sap-automation/deploy/ansible/download_menu.sh

ASK [roles-sap/0.1-bom-validator : BOM: S41909SPS03_v0008ms Download File SWPM20SP10_3-80003424.SAR] ****************************************************************************************
fatal: [localhost]: FAILED! => {"attempts": 1, "changed": false, "dest": "/mnt/downloads/files/SWPM20SP10_3-80003424.SAR", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://softwaredownloads.sap.com/file/0020000001808612021"}

Changes made to ~/Azure_SAP_Automated_Deployment/sap-automation/deploy/ansible/BOM-catalog/S41909SPS03_v0008ms/S41909SPS03_v0008ms.yaml

#Comments
before:

name:    'S41909SPS03_v0006ms'
target:  'S/4 HANA 1909 SPS 03'
version: 7

after:

name:    'S41909SPS03_v0008ms'
target:  'S/4 HANA 1909 SPS 03'
version: 8

# SWPM
before:

    - name:         "SWPM20SP10; OS: Linux on x86_64 64bit"
      archive:      SWPM20SP10_3-80003424.SAR
      checksum:     1d8cf46f4ad43aea7eca0174fb1b6d9fb1e01bde5d9882388064dc10d61a0495
      extract:      true
      extractDir:   SWPM
      creates:      SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000001808612021

after:

    - name:         "SWPM20SP10; OS: Linux on x86_64 64bit"
      archive:      SWPM20SP10_4-80003424.SAR
      checksum:     8dcdf68d52d95a2a1aa7322ef986a1154b36269fd07313bd1afe48013c07b4ee
      extract:      true
      extractDir:   SWPM
      creates:      SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000001848492021

#SUM
before:

    - name:         "Patch 4 for SOFTWARE UPDATE MANAGER 2.0 SP12 ; OS: Linux on x86_64 64bit"
      archive:      SUM20SP12_4-80002456.SAR
      checksum:     dd1b677342bbda47d9585fffc6a7107f845b41b3d114f895d954c19d70987087
      download:     false
      url:          https://softwaredownloads.sap.com/file/0020000001731572021

after:

    - name:         "Patch 5 for SOFTWARE UPDATE MANAGER 2.0 SP12 ; OS: Linux on x86_64 64bit"
      archive:      SUM20SP12_5-80002456.SAR
      checksum:     c774960a82d651e57bec8f0de436e3d7d6859ed6bbf08ec25306b6678d5f1a28
      download:     false
      url:          https://softwaredownloads.sap.com/file/0020000001834832021

**Comment by hdamecharla** [comment]
Hi @enterprise-1701-d, thank you for raising the issue.

I have raised a new PR #22 to resolve this issue. 

Thank you 🙏🏾

**Comment by 1lomeno3** [comment]
I need to report that all NW based BOMs are now outdated, like BW4HANA2021SPS01_v0002ms (missing SUM20SP12_4-80002456.SAR), NW750SPS20_v0003ms (SWPM10SP33_2-20009701.SAR) or SOLMAN72FPS12_v0001ms (SWPM10SP31_6-20009701.SAR).

**Comment by enterprise-1701-d** [comment]
Description how to create own BOMs is offerend in the documentation. Therefore everybody is able to adjust the BOMs on its own. 

https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-software
