### ISSUE TITLE
[Feature] provide customer specific placeholder playbook in configuration_menu.sh before Base OS Config

### ISSUE THREAD

**Issue by enterprise-1701-d** [Azure/sap-automation#20]
**Is your feature request related to a problem? Please describe.**
I need to use BYOS images and therefore they have to be registered first with SUSE or RedHat

**Describe the solution you'd like**
I would like to have a Step "0) Customer specific Preparations" where I could include the registration of all VMs based on the generated hosts file

~/Azure_SAP_Automated_Deployment/sap-automation/deploy/ansible/configuration_menu.sh
0) Customer specific Preparations
1) Base OS Config	      
2) SAP specific OS Config     
3) BOM Processing	     

**Describe alternatives you've considered**
well I used an own playbook to register the systems with SUSE in my particular case and than started with step 1)

**Additional context**

here is my task I added to the playbook_01
suse-register.yml

- name: Register SuseConnect
  command: "SUSEConnect -r <key> -e <email>"
  args:
    creates: "/etc/zypp/credentials.d/SCCcredentials"
  tags: 
  - deployment

Well of course the credentials could be in a key vault - asking interactively or prepare it similar to the S-User keyvault entries

Problem DB-Hosts were not able to register to SUSE, but APP-Servers ware able. I think it might be some NSG-Rule or something, which prevents access to the internet.

**Comment by mimergel** [comment]
Hi, if you deployed without firewall then HDB and SCS won't have access to the repository server due to their load balancers being deployer per default. The nw communication blocks due to the missing FW. In that case pls disable LBs during deployments: 
Set this in the SYSTEM tfvars file: 
use_loadbalancers_for_standalone_deployments=false
Afterwards all VMs can connect. 
Hope this helps and thanks for the suggestion to have a placeholder playbook where customer specific tasks can be added.

**Comment by sapien47** [comment]
Had the same issue, I attached a NAT gateway to allow the SUSE Registration.
As for the possibility to register your BYOS Linux licenses, I second that.
Most of your customers are coming from SAP on Premises, where they already own licenses.

Thanks

**Comment by PankajMeshramCSA** [comment]
@mimergel - could we please check if this can be closed ?

**Comment by hdamecharla** [comment]
The extensibility portion of the framework is now live in the latest release. 

You can create a playbook with custom tasks to extend the framework.

The playbooks should be in the workspaces repo under Ansible folder, suffixed by _pre and _post. 

Please see below image for more information.

![image](https://github.com/Azure/sap-automation/assets/71097261/159d6ca6-6be5-459b-b7cf-b8ab763d8e80)

**Comment by PmeshramPM** [comment]
closing this issue based on the info from @hdamecharla
