### ISSUE TITLE
[BUG] ERROR: Please run 'az login' to setup account. during pipeline 4 SAP software acquisition

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#212]
**Describe the bug**
Pipeline 4:
TASK [roles-misc/0.2-kv-secrets : BoM Secrets: Retrieve S User detail secret] ***
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["az", "keyvault", "secret", "show", "--vault-name", "MGMTNOEUDEP02user483", "--name", "S-Username"], "delta": "0:00:02.629802", "end": "2022-07-07 13:10:14.104474", "msg": "non-zero return code", "rc": 1, "start": "2022-07-07 13:10:11.474672", "stderr": "ERROR: Please run 'az login' to setup account.", "stderr_lines": ["ERROR: Please run 'az login' to setup account."], "stdout": "", "stdout_lines": []}

**To reproduce**
deploy control plane with parameter
auto_configure_deployer = true

**Expected behavior**
agent software has all required environments so that this issue doesn't happen

**Additional context**
can be fixed by uninstalling and installing the devops agent software again on the deploy

**Comment by mimergel** [comment]
here are the workaround steps to re-install the devops agent software on the deployer

```
cd agent
sudo ./svc.sh stop
sudo ./svc.sh uninstall
./config.sh remove # (PAT wird benöigt)
cd $HOME
mv agent agent.old
wget https://vstsagentpackage.azureedge.net/agent/2.204.0/vsts-agent-linux-x64-2.204.0.tar.gz
mkdir agent && cd agent
tar -xzvf ../vsts-agent-linux-x64-2.204.0.tar.gz
./config.sh # (DevOPS Url, PAT & Pool Name eingeben)
sudo ./svc.sh install
sudo ./svc.sh start
```

**Comment by enterprise-1701-d** [comment]
Hi @mimergel, I did perform everything as stated in your comment to provide the workaround. It still doesn't work. The result is still hat asks to az login again. I used branch "experimental". I have a MSDN subscription, so there are no policies etc. which might block access. Especially in the first run, it perfectly adds S-Username and S-Passwort to the keyvault, but is not able to obtain it from there in the next step. Strange.
Please find below the already known output:


TASK [roles-misc/0.2-kv-secrets : BoM Secrets: Retrieve S User detail secret] ***
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["az", "keyvault", "secret", "show", "--vault-name", "MGMTWEEUDEP00user11B", "--name", "S-Username"], "delta": "0:00:02.039486", "end": "2022-08-31 06:29:30.535934", "msg": "non-zero return code", "rc": 1, "start": "2022-08-31 06:29:28.496448", "stderr": "ERROR: Please run 'az login' to setup account.", "stderr_lines": ["ERROR: Please run 'az login' to setup account."], "stdout": "", "stdout_lines": []}

**Comment by mimergel** [comment]
Hi @enterprise-1701-d , the issue has been resolved somewhere in July. Can you update your code and try again? If I remember correctly you'll need to deploy the agent again.

**Comment by mimergel** [comment]
issue has been fixed. Agent need to be deployed again to get it working.
