### ISSUE TITLE
[FEATURE]  set-up-an-azure-shared-disk-sbd-device

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#215]
**Is your feature request related to a problem? Please describe.**
Please add the possibly to use a shared disk as SBD device.

**Describe the solution you'd like**
As described in here: 
https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#set-up-an-azure-shared-disk-sbd-device

**Describe alternatives you've considered**
- iSCSI devices require additional VM, so this is not a preferred option. 
- Azure Fencing Agent requires a connection to azure public endpoints and a firewall entry. 
- SBD device on shared disks seems the best and easiest option

**Additional context**

**Comment by PankajMeshramCSA** [comment]
@mimergel  - are you working on this one ?
