### ISSUE TITLE
Getting Authentication error in azure cloud shell while running terraform commands

### ISSUE THREAD

**Issue by bmopati** [Azure/sap-automation#221]
**Describe the bug**
I am getting an authentication error while logging in azure cloud shell to run terraform commands

**To reproduce**
1. Go to azure cloud shell
2. enter "az login"
3. login to the account and set the correct subscription
4. run terraform command See error

Error:-

WARNING: A Cloud Shell credential problem occurred. When you report the issue with the error below, please mention the hostname 'cc-aa3f5bb3-6fd7bc764f-r2tnt'
ERROR: AADSTS53000: Device is not in required device state: compliant. Conditional Access policy requires a compliant device, and the device is not compliant. The user must enroll their device with an approved MDM provider like Intune.
Trace ID: f1e0d559-c4d0-428e-98d8-d059c9fc6b00
Correlation ID: d64bc76c-627d-4dbb-9eef-42e06b1d0853
Timestamp: 2022-07-19 13:46:27Z
To re-authenticate, please run:
az login --scope https://graph.microsoft.com//.default
WARNING: A Cloud Shell credential problem occurred. When you report the issue with the error below, please mention the hostname 'cc-aa3f5bb3-6fd7bc764f-r2tnt'
ERROR: AADSTS53000: Device is not in required device state: compliant. Conditional Access policy requires a compliant device, and the device is not compliant. The user must enroll their device with an approved MDM provider like Intune.
Trace ID: f1e0d559-c4d0-428e-98d8-d059c9fc6b00
Correlation ID: d64bc76c-627d-4dbb-9eef-42e06b1d0853
Timestamp: 2022-07-19 13:46:27Z
To re-authenticate, please run:
az login --scope https://graph.microsoft.com//.default

**Expected behavior**
commands should have worked normally.

**Additional context**
az login --scope https://graph.microsoft.com//.default 
logging in using the above command is showing that device needs to be microsoft managed

**Comment by jkirkmannz** [comment]
Likely to be an issue with your corporate Azure AD security policy & Conditional Access.

**Comment by PankajMeshramCSA** [comment]
@bmopati  - This seems an issue with your corporate Security polices based on the error messages. Could you please check and confirm the closure.

**Comment by jhajduk-microsoft** [comment]
@bmopati - As mentioned above, this is likely an error with your tenant. can you specify exactly what Terraform command you are running and at what stage you are being asked to log in?

**Comment by jhajduk-microsoft** [comment]
@bmopati - Were you able to check your organization policies and device compliance?
