### ISSUE TITLE
[BUG] : sap-automation/deploy/ansible/playbook_bom_downloader.yaml -> Failed 

### ISSUE THREAD

**Issue by SenthilKumar2u** [Azure/sap-automation#226]
Hello ,

I am following the below link steps to perform SAP install through Azure solutions for SAP.

https://docs.microsoft.com/en-us/azure/center-sap-solutions/install-software

I have completed all the preparation steps and working on this topic "Download SAP media"

** Steps to reproduce the behavior** 

While running the ansible playbook to download SAP media via "/sap-automation/deploy/ansible/playbook_bom_downloader.yaml"
getting the below error.

ansible-playbook ./sap-automation/deploy/ansible/playbook_bom_downloader.yaml -e "bom_base_name=S41909SPS03_v0011ms" -e "deployer_kv_name=abcd" -e "s_user=<username>" -e "s_password=<password>" -e "sapbits_access_key=<storageAccountAccessKey>" -e "sapbits_location_base_path=<containerBasePath>" -e "sapbits_sas_token=<containerSasToken>"

** ERROR**

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [BOM Downloader Playbook] *********************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
ok: [localhost]

TASK [BOM Downloader: Show the BOM] ****************************************************************************************************
ok: [localhost] => {
    "bom_base_name": "S41909SPS03_v0011ms",
    "changed": false
}

TASK [Set the bom tier] ****************************************************************************************************************
ok: [localhost]

TASK [BOM Downloader: Set deployer keyvault name] **************************************************************************************
skipping: [localhost]

TASK [BOM Downloader: Load the keyvault secrets] ***************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr fo
r the exact error", "rc": 0}

**Expected behavior**
if I run the ansible playbook , it has to download SAP media based on our information.
![github_error](https://user-images.githubusercontent.com/105032414/180504133-14898798-2294-43a0-8aa5-d107a78ba394.JPG)

**Additional context**

**Comment by SenthilKumar2u** [comment]
Hello , I received the below suggestion from Azure SAP team and followed the same steps to fix the issue.

Root cause: 
The script(DownloadDeployerVMPackages.sh) URL seems incorrect in our document  ([https://raw.githubusercontent.com/Azure/ACSS-preview/main/Installation%20Script/DownloadDeployerVMPackages.sh](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FACSS-preview%2Fmain%2FInstallation%2520Script%2FDownloadDeployerVMPackages.sh&data=05%7C01%7CMarco.Cruz%40microsoft.com%7Cdd8f93edd4f6412e074908da7146fab2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637946846983478021%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SHBqjhMFjE6L0zcq3KkDL%2Bfe0drlr9acbIG9v4e5whg%3D&reserved=0)
      [Correct URL: [https://raw.githubusercontent.com/Azure/Azure-Center-for-SAP-solutions-preview/main/DownloadDeployerVMPackages.sh](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Center-for-SAP-solutions-preview%2Fmain%2FDownloadDeployerVMPackages.sh&data=05%7C01%7CMarco.Cruz%40microsoft.com%7Cdd8f93edd4f6412e074908da7146fab2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637946846983478021%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RSAPQNR4NPaBoBC7S%2B%2FXM6w%2FgWp77mlR3SZDn9pvENA%3D&reserved=0) ]



Mitigation plan: 
1.	Customer can use the updated URL to execute the DownloadDeployerVMPackages.sh , as stated above.
[https://raw.githubusercontent.com/Azure/Azure-Center-for-SAP-solutions-preview/main/DownloadDeployerVMPackages.sh](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Center-for-SAP-solutions-preview%2Fmain%2FDownloadDeployerVMPackages.sh&data=05%7C01%7CMarco.Cruz%40microsoft.com%7Cdd8f93edd4f6412e074908da7146fab2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637946846983635003%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6NeQtGTZqdByCLUgBXAkBXgPD%2BG8b4Lmvj%2B%2Fb8D1Vpo%3D&reserved=0) 
2.	Subsequently, they can retry the install from Azure portal.


Thanks & Regards,
Senthil Kumar.S

**Comment by debi74** [comment]
Hi Senthil,

Thanks you solved the issue. In my case, I am also facing the issue as below :
![image](https://user-images.githubusercontent.com/90674178/184086164-5f7a2507-b82b-4910-8ba9-45a713c1527e.png)

Then , i ran again the same command without <containerSasToken> part, and it started to download the SAP media file . Did you got this kind of issue as well?

Thanks
Debi Prasad

**Comment by SenthilKumar2u** [comment]
Hello, I have received the below error while running the script.

TASK [BOM Downloader: Load the keyvault secrets] ***************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr fo
r the exact error", "rc": 0}

PLAY RECAP *****************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

 **FIX**  : Install the latest Terraform , Pyton and ansible. For more details check the below URL and Video.

https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-manual-deployment

https://www.youtube.com/watch?v=WnT606q7wHo

**Comment by debi74** [comment]
Thanks. Now I am able to complete the installation. But what is the default SAP user to login to the SAP application via SAP GUI and what is the HANA DB system user password to use?

Thanks,

**Comment by SenthilKumar2u** [comment]
Hello Debi Prasad,
I found the link below but was not able to find DB and SAP standard password. you may activate SAP* user in the DEFAULT.PFL and restart the instance to login SAP via SAPGui for validation. Have you performed a standalone or HA SAP install ?

https://docs.microsoft.com/en-us/azure/center-sap-solutions/manage-virtual-instance#find-sap-and-hana-passwords

**Comment by debi74** [comment]
Hi,

I have installed distributed non-production system. I already saw that link and can see the password of SAP system.

Thanks,
Debi

**Comment by jkirkmannz** [comment]
Have a look in the key vault! They are all stored there.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
