### ISSUE TITLE
sap-automation deployment issue

### ISSUE THREAD

**Issue by nehavijapur-1** [Azure/sap-automation#228]
We cloned Main Branch to our azure repository and configure control plane deployment with few parameter changes in file(WORKSPACES/DEPLOYER/MGMT-WEEU-DEP00-INFRASTRUCTURE/MGMT-WEEU-DEP00-INFRASTRUCTURE.tfvars) like 
bastion_deployment=true, deployer_enable_public_ip=true. After enabling both Bastion and Public IP address  and run the deployment. We are getting below error.

_Error in Text -_ 
**Error: remote-exec provisioner error
  with module.sap_deployer.null_resource.prepare-deployer[0],
  on ../../terraform-units/modules/sap_deployer/configure-deployer.tf line 39, in resource "null_resource" "prepare-deployer":
  39:   provisioner "remote-exec" {

error executing "/tmp/terraform_1958996308.sh": Process exited with status 2
##[error]Error: remote-exec provisioner error
##[error]Return code from prepare_region 11.
##[error]Error message: Migrating the deployer state failed.**

_Error Image -_ 
![image](https://user-images.githubusercontent.com/109970266/180795666-0c28af00-2025-4d00-88f3-fc24743c7283.png)

**Comment by barisberkbulut** [comment]
Hi, there should be error outputs above the lines you have pasted in SS. They're colored in gray so be mindful to everything above that red errors. There should be the key error that what's causing it to fail.

**Comment by enterprise-1701-d** [comment]
The last line says:
module.sap_deployer.null_resource.prepare-deployer[0] (remote-exec): chmod: changing permissions of '/home/azureadm/agent/config_fixed_params.sh': Operation not permitted


I created a logfile with -vvv option of the script /Azure_SAP_Automated_Deployment/sap-automation/deploy/scripts/configure_deployer.sh
[log.txt](https://github.com/Azure/sap-automation/files/9434346/log.txt)

**Comment by enterprise-1701-d** [comment]
I can clean up the whole Azure subscription, repo and repeat everything from scratch - it is not working using the pipelines from main branch. The error stays: module.sap_deployer.null_resource.prepare-deployer[0] (remote-exec): 
chmod: changing permissions of '/home/azureadm/agent/config_fixed_params.sh': Operation not permitted

+ sudo chmod -R 777 /home/azureadm/agent
+ cd /home/azureadm/agent
+ ./env.sh
+ sudo tee -a /home/azureadm/agent/config_fixed_params.sh
echo /home/azureadm/agent/config.sh --unattended --url https://dev.azure.com/organization0343/ --auth pat --token bw24vn53jreemvn4rw3df7buc72btzdxqw37 --pool POOL --agent mgmtweeudep00deploy00 --replace --acceptTeeEula
(remote-exec): /home/azureadm/agent/config.sh --unattended --url https://dev.azure.com/organization0343/ --auth pat --token bw24vn53jreemvn4rw3df7buc72btzdxqw37 --pool POOL --agent mgmtweeudep00deploy00 --replace --acceptTeeEula

(remote-exec): + chmod +x /home/azureadm/agent/config_fixed_params.sh
(remote-exec): chmod: changing permissions of '/home/azureadm/agent/config_fixed_params.sh': Operation not permitted


On the operating system the script "prepare_deployer.sh" finishes.
azureadm@mgmtweeudep00deploy00:~/Azure_SAP_Automated_Deployment/sap-automation/deploy/scripts$ ./configure_deployer.sh

**Comment by PankajMeshramCSA** [comment]
@nehavijapur-1  - Could you please check the new process here and confirm?   https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-devops-tutorial
