### ISSUE TITLE
Key Vault Already Exists Error in Control Plane Deployment [BUG]

### ISSUE THREAD

**Issue by barisberkbulut** [Azure/sap-automation#231]
**Describe the bug**
I get the following error when i try to deploy Control Panel via Azure Devops Pipeline :

"A resource with the ID "/subscriptions/XXXXXXXXXX/resourceGroups/MGMT-WEEU-DEP01-INFRASTRUCTURE/providers/Microsoft.KeyVault/vaults/MGMTWEEUDEP01user98D/objectId/8100e3b8-ab10-43ac-9465-6bbc8ba02694" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information."

My azure, is totally empty there is no resource that could give me the "exists" error. Even though autmation creates it with a random name in every run, i wanted to make sure and deleted everything before the deployment. It creates the Key Vault and then gives the error.

**Comment by enterprise-1701-d** [comment]
@barisberkbulut Did you find any solution?
I observed the same error but only when I am rerunning the Pipeline (Deploying the control plane) which run successfully the first time (so when Azure was completely empty). I wanted to check whether Terraform is aware of everything and therefore rerun the pipeline (Deploying the control plane) again - 
Interesting is the fact that Terraform will recreate 2 items, although they exist: sapbits-location-base-path and sapbits-access-key and so I got the following error:

Terraform will perform the following actions:

  # module.sap_library.azurerm_key_vault_secret.sapbits_location_base_path[0] will be created
  + resource "azurerm_key_vault_secret" "sapbits_location_base_path" {
      + id                      = (known after apply)
      + key_vault_id            = "/subscriptions/13f22992-de24-4eae-8547-aa77252834da/resourceGroups/MGMT-WEEU-DEP01-INFRASTRUCTURE/providers/Microsoft.KeyVault/vaults/MGMTWEEUDEP01userFB1"
      + name                    = "sapbits-location-base-path"
      + resource_id             = (known after apply)
      + resource_versionless_id = (known after apply)
      + value                   = (sensitive value)
      + version                 = (known after apply)
      + versionless_id          = (known after apply)
    }

  # module.sap_library.azurerm_key_vault_secret.saplibrary_access_key[0] will be created
  + resource "azurerm_key_vault_secret" "saplibrary_access_key" {
      + id                      = (known after apply)
      + key_vault_id            = "/subscriptions/13f22992-de24-4eae-8547-aa77252834da/resourceGroups/MGMT-WEEU-DEP01-INFRASTRUCTURE/providers/Microsoft.KeyVault/vaults/MGMTWEEUDEP01userFB1"
      + name                    = "sapbits-access-key"
      + resource_id             = (known after apply)
      + resource_versionless_id = (known after apply)
      + value                   = (sensitive value)
      + version                 = (known after apply)
      + versionless_id          = (known after apply)
    }
