### ISSUE TITLE
Azure center for sap solutions : Feedback

### ISSUE THREAD

**Issue by SenthilKumar2u** [Azure/sap-automation#238]
Hello , 
I have installed the SAP S/4 HANA single/standalone server by using Azure center for SAP solutions tool. It`s a great and innovation tool and prompted me to enter only basic details like subscription , Resource group , SAP SID , Network and OS image details.

**Describe the solution you'd like**
I feel there are some limitations in the tool.  If possible, add the below functions in the next release. It will be more useful to customers.

1. Not able to enter customized SAP System number and password for SAP and DB users.
2. Limited OS options only available for SAP PAS/AAS server (windows image is missing).
3. After install I need to adjust to increase / decrease H/W Size. Not able to customize H/W size based on SAPs Value.
4. Before creating a server , please display the SAP and DB file system details and allow us to change file system size.
5. Azure released this tool only for the new SAP S/4 Install. Please enhance the same functionality for other SAP supported DB`s and SAP versions.

**Comment by PankajMeshramCSA** [comment]
@SenthilKumar2u  - ACSS repo is different from the SDAF repo. With SDAF you have all the options that you have mentioned. For ACSS please raise the feedback here -> https://feedback.azure.com/d365community/forum/9ed90375-d5e0-ec11-bb3d-000d3a57bc26
