### ISSUE TITLE
[BUG] HTTP Error 409: Public access is not permitted on this storage account in Software Acquisition / Configuration and SAP Installation

### ISSUE THREAD

**Issue by barisberkbulut** [Azure/sap-automation#240]
I get the following errors when try to run DB and SAP installation pipeline in Azure Devops.

TASK [**roles-sap/3.3.1-bom-utility : 3.3.1 BoM Processing**: S41909SPS03_v0011ms Check is file S41909SPS03_v0011ms is already downloaded to the storage account] ***
fatal: [x00scs00lab8 -> localhost]: FAILED! => {"changed": false, "dest": "/mnt/downloads/bom/S41909SPS03_v0011ms.yaml", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 409: Public access is not permitted on this storage account.", "status_code": 409, "url": "[https://mgmtweeusaplibe51.blob.core.windows.net/sapbits/sapfiles/boms/S41909SPS03_v0011ms/S41909SPS03_v0011ms.yaml?"}](https://mgmtweeusaplibe51.blob.core.windows.net/sapbits/sapfiles/boms/S41909SPS03_v0011ms/S41909SPS03_v0011ms.yaml?%22})

anyone faced this issue?

**Comment by jhajduk-microsoft** [comment]
Will attempt to repro

**Comment by jhajduk-microsoft** [comment]
@barisberkbulut - Can you check if there is a firewall on the storage account and double check the SAS token?
