### ISSUE TITLE
[Feature] FAILED - RETRYING: DBLoad Install -Wait for asynchronous job to end (120 retries left).

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#268]
**Is your feature request related to a problem? Please describe.**
Improve Pipeline 5 dbload output: 
  TASK [roles-sap/5.1-dbload : DBLoad: - run SAPInst] ****************************
  changed: [x00scs00lc25]
  FAILED - RETRYING: DBLoad Install -Wait for asynchronous job to end (120 retries left).

**Describe the solution you'd like**
  The word "failed" is misleading here because the DB load is still running.
  Users get confused and believe something is wrong although everything is running fine.

*Describe alternatives you've considered**
none

**Additional context**
none

**Comment by KimForss** [comment]
The challenge here is that failed is coming from Ansible and we are unable to change the wording, will investigate
