### ISSUE TITLE
[Feature] Please add Azure Bastion Service as option 

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#27]
**Problem statement**
Often customers and partner do not wish to have a public IP on the deployer VM.
Then it becomes complicated for them to connect to it. 
Azure bastion would help very much. 

**Enhancement**
Please add the possibility to deploy the Azure bastion service as part of the prepare region step

**Notes**
n.a.

**Dependencies**
n.a.

**Checklist**
n.a.

**Comment by PankajMeshramCSA** [comment]
@mimergel - We have the bastion option now. Could you please confirm to close this one? Thanks

**Comment by mimergel** [comment]
confirmed. many thanks!
