### ISSUE TITLE
New version release 

### ISSUE THREAD

**Issue by Rickmarges** [Azure/sap-automation#270]
**Is your feature request related to a problem? Please describe.**
The current version tag is way out of date, resulting in a lot of missing functionality when using a specific version

**Describe the solution you'd like**
A new released version of sap-automation (at least v3.4.2.0 or greater)

**Comment by Rickmarges** [comment]
@KimForss Can you please release a new version to use?

**Comment by KimForss** [comment]
Hi

I will do that once my Net App deployment finishes – hopefully in a few hours. I pushed a bunch of updates yesterday and want to finalize the testing to ensure there are no regressions

//Kimmo

**Comment by Rickmarges** [comment]
@KimForss Good morning. I noticed yesterday a commit was made with the message "Version 3.5 release". That's some great news! Is it also possible to add a version tag to the repo?

**Comment by KimForss** [comment]
I will once I validate that nothing is broken 😊

**Comment by Rickmarges** [comment]
Great, Thank you!
