### ISSUE TITLE
[BUG] SOFTWARE UPDATE MANAGER 2.0 SP14 Patch 6 is no longer available

### ISSUE THREAD

**Issue by yertaylan67** [Azure/sap-automation#289]
**Describe the bug**
Please update the BOM catalog for SUM20SP14_latest. SOFTWARE UPDATE MANAGER 2.0 SP14 Patch 6 is no longer available. SAP replaced it by Patch 7.

**To reproduce**

**Expected behavior**

**Additional context**

**Comment by enterprise-1701-d** [comment]
@yertaylan67 you have to adjust the BOM manually with the versions SAP changes to often. Provide the new file details (name, URL, hash, etc.) commit the change and rerun the pipeline.

**Comment by enterprise-1701-d** [comment]
Please find here the updated code block for file deploy/ansible/BOM-catalog/SUM20SP14_latest/SUM20SP14_latest.yaml:

```
---
name:    'SUM20SP14'
target:  'SUM20SP14'
version: 007

materials:

  media:
   # SUM
    - name:         "Patch 7 for SOFTWARE UPDATE MANAGER 2.0 SP14"
      archive:      SUM20SP14_7-80002456.SAR
      checksum:     b207e0c1b832e50603a46b6e678d1f2eea63750acee49d7cdc9403f29257278c
      download:     false
      url:          https://softwaredownloads.sap.com/file/0020000001246852022
      
    - name:         "Patch 7 for SOFTWARE UPDATE MANAGER 2.0 SP14 (Windows)"
      archive:      SUM20SP14_7-80002458.SAR
      checksum:     73c72687e291992f4f0b605c6ee6111e4d0d667d50c310fb6816aaadff700612
      download:     false
      url:          https://softwaredownloads.sap.com/file/0020000001246872022
```

**Comment by KimForss** [comment]
@yertaylan67 This resolved in the repo, closing
