### ISSUE TITLE
[BUG] Incorrect HANA VM and NIC names when HA and AvZones deployment is used

### ISSUE THREAD

**Issue by 1lomeno3** [Azure/sap-automation#29]
**Describe the bug**
When HA is enabled (modedatabase_high_availability=true) and AvZones are specified (e.g. database_vm_zones=["2","3"]), the name of both HANA VM and related NICs contain only the first zone number:
- DEV-WEEU-SAP01-HDB_hdbdhdb_z2_00l0b9e
- DEV-WEEU-SAP01-HDB_hdbdhdb_z2_00l1b9e

**Expected behaviour**
Expected name of resources should be:
- DEV-WEEU-SAP01-HDB_hdbdhdb_z2_00l0b9e
- DEV-WEEU-SAP01-HDB_hdbdhdb_z3_00l0b9e

**Comment by PankajMeshramCSA** [comment]
@hdamecharla - Coud you please check if this is an easy fix? Possibly, we may have already fixed it by now.

**Comment by hdamecharla** [comment]
Hi @1lomeno3 , thank you for raising the bug and helping us improve the solution. 

This should be fixed as part of commit -[b91a1cf](https://github.com/Azure/sap-automation/commit/b91a1cf146fe432ed18d6f16f069bf2c5cee39f8#diff-dd6be9aac7ef18aa2744baac5d39e2e05955dea5e569d019f3af01873e4d2ef5)
