### ISSUE TITLE
[BUG] Unsupported attributes username and sshkey during deployer configuration

### ISSUE THREAD

**Issue by 1lomeno3** [Azure/sap-automation#3]
**Describe the bug**
Error: Unsupported attribute
│
│   on ../../terraform-units/modules/sap_deployer/configure-deployer.tf line 16, in resource "null_resource" "prepare-deployer":
│   16:     user        = var.deployer.authentication.username
│     ├────────────────
│     │ var.deployer.authentication is object with 1 attribute "type"
│
│ This object does not have an attribute named "username".
╵
╷
│ Error: Unsupported attribute
│
│   on ../../terraform-units/modules/sap_deployer/configure-deployer.tf line 17, in resource "null_resource" "prepare-deployer":
│   17:     private_key = var.deployer.authentication.type == "key" ? var.deployer.authentication.sshkey.private_key : null
│     ├────────────────
│     │ var.deployer.authentication is object with 1 attribute "type"
│
│ This object does not have an attribute named "sshkey".

**Comment by hdamecharla** [comment]
Hi @1lomeno3, thank you for raising the issue. 

The problematic code was fixed as part of 695bee24c7688debedb7edf22481aae346e43b7b

Kindly re-open the issue if you are still facing the same problem.
