### ISSUE TITLE
[BUG] No repositories defined during Base OS Config and SAP specific OS Config playbooks

### ISSUE THREAD

**Issue by 1lomeno3** [Azure/sap-automation#30]
**Describe the bug**
When running SAP installation with options 1) Base OS Config  and 2) SAP specific OS Config I get error during the task roles-os/1.3-repository : Check that zypper repos are registered:

fatal: [hdbscs00lb9e]: FAILED! => {"changed": false, "cmd": ["zypper", "lr"], "delta": "0:00:00.798262", "end": "2022-01-07 08:37:47.944257", "msg": "non-zero return code", "rc": 6, "start": "2022-01-07 08:37:47.145995", "stderr": "", "stderr_lines": [], "stdout": "Warning: No repositories defined.\nUse the 'zypper addrepo' command to add one or more repositories.", "stdout_lines": ["Warning: No repositories defined.", "Use the 'zypper addrepo' command to add one or more repositories."]}

**Comment by 1lomeno3** [comment]
The issue was caused by missing FW in the deployer zone and therefore there was no outbound connectivity from the VMs behind ILB.
I would therefore suggest removing the BUG label and change it to FEATURE request or suggestion in the documentation specifying that either FW or additional load balancer is needed in order to have a cluster functional.

**Comment by hdamecharla** [comment]
This is part of the SAP on Azure documentation [here](https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse).
