### ISSUE TITLE
[BUG] Deploy the Workload Zone - spn_id and client_id

### ISSUE THREAD

**Issue by BillCarsson** [Azure/sap-automation#303]
**Describe the bug**
Trying to reproduce the SAP framwork hands-up lab. Unable to deploy the workload-zone. Probably a bug in /deploy/scripts/install_workloadzone.sh.

**To reproduce**
Follow steps described in Enterprise Scale for SAP deployment automation framework - Hands-on Lab](https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-tutorial#deploy-the-workload-zone) :
1. Got an error when executing ${DEPLOYMENT_REPO_PATH}/deploy/scripts/install_workloadzone.sh from control plan Deployer vm
2. As described in documentation, all env vars set
3. install_workloadzone.sh output : 
```
#########################################################################################
#                                                                                       #
#       The provided client_id is not valid: --client_id                                #
#                                                                                       #
#########################################################################################
```

**A workaround**
Found a workaround. In addition of : export spn_id=xxxxx, i added  export client_id=xxxxxx

**Comment by KimForss** [comment]
Thanks Bill, I'll check to see if it is a documentation or a script bug
