### ISSUE TITLE
Workload Zone Deployment Access Issue

### ISSUE THREAD

**Issue by nehavijapur-1** [Azure/sap-automation#316]
We have SdafdeployerKv keyvault and private endpoint created in control plane deployment subscription.
While deploying the workload zone we are getting Access Issue.

![image](https://user-images.githubusercontent.com/109970266/196621279-44738672-1598-4107-a6d0-02f22a092c05.png)

Though we give full permission to keyvault , after re-running the pipeline the permission are vanishing.

**Comment by PankajMeshramCSA** [comment]
Hi @nehavijapur-1  - This has been fixed by our recent release 3.6. Could you please check and confirm?
