### ISSUE TITLE
[BUG] Deploy the Workload Zone - Parameter file does not exist

### ISSUE THREAD

**Issue by jakristensen** [Azure/sap-automation#320]
**Describe the bug**
Trying to deploy the Workload Zone. I suspect there is a bug in 

**To reproduce**
Follow steps described in Enterprise Scale for SAP deployment automation framework - Hands-on Lab](https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-tutorial#deploy-the-workload-zone) :
1. Got an error when executing ${DEPLOYMENT_REPO_PATH}/deploy/scripts/install_workloadzone.sh from control plan Deployer vm
2. As described in documentation, all env vars set
3. install_workloadzone.sh output :

4. 
```
#########################################################
#                                                                                                                       #
#                  Parameter file does not exist:                                                      #
#                                                                                                                      #
########################################################
```
I have not been able to figure out a workaround

**Comment by nnoaman** [comment]
Could you please confirm that "sap-parameters.yaml" file is existing? As per the steps in the below screenshot
![image](https://user-images.githubusercontent.com/95418928/198610838-b3dc1bf8-aaed-4400-a0ba-ab9d9941dd40.png)

**Comment by nnoaman** [comment]
Could you please ensure that you've updated the below <region_code> and <vaultID> with the values of your env, and also navigated to the right directory? 

`export tfstate_storage_account="<storageaccountName>"
export       deployer_env_code="MGMT"
export            sap_env_code="DEV"
export             region_code="<region_code>"
export               key_vault="<vaultID>"

cd ~/Azure_SAP_Automated_Deployment/WORKSPACES/LANDSCAPE/${sap_env_code}-${region_code}-SAP01-INFRASTRUCTURE
`

**Comment by cjpark-sapcsa** [comment]
@jakristensen  any chance to find out the workaround ? 

I have a file in the folder , DEV-WEEU-SAP01-INFRASTRUCTURE.tfvars, but the script is not pickup fie 


azureadm@mgmtweeudep00deploy00:~/Azure_SAP_Automated_Deployment/WORKSPACES/LANDSCAPE/DEV-WEEU-SAP01-INFRASTRUCTURE$ ls -la
total 36
drwxr-xr-x 2 azureadm azureadm  4096 Jan 25 09:25 .
drwxr-xr-x 3 azureadm root      4096 Jan 26 04:22 ..
-rw-r--r-- 1 azureadm azureadm 24961 Jan 25 09:25 DEV-WEEU-SAP01-INFRASTRUCTURE.tfvars
azureadm@mgmtweeudep00deploy00:~/Azure_SAP_Automated_Deployment/WORKSPACES/LANDSCAPE/DEV-WEEU-SAP01-INFRASTRUCTURE$ ${DEPLOYMENT_REPO_PAT
H}/deploy/scripts/install_workloadzone.sh                                          \
> 
Deployer environment: 

#########################################################################################
#                                                                                       #
#                  Parameter file does not exist:                                          #
#                                                                                       #
#########################################################################################
azureadm@mgmtweeudep00deploy00:~/Azure_SAP_Automated_Deployment/WORKSPACES/LANDSCAPE/DEV-WEEU-SAP01-INFRASTRUCTURE$     --parameterfile .
/${sap_env_code}-${region_code}-SAP01-INFRASTRUCTURE.tfvars                        \
> 
--parameterfile: command not found
azureadm@mgmtweeudep00deploy00:~/Azure_SAP_Automated_Deployment/WORKSPACES/LANDSCAPE/DEV-WEEU-SAP01-INFRASTRUCTURE$     --deployer_enviro
nment "${deployer_env_code}"                                                       \
> 
--deployer_environment: command not found
azureadm@mgmtweeudep00deploy00:~/Azure_SAP_Automated_Deployment/WORKSPACES/LANDSCAPE/DEV-WEEU-SAP01-INFRASTRUCTURE$     --deployer_tfstat
e_key "${deployer_env_code}-${region_code}-DEP00-INFRASTRUCTURE.terraform.tfstate" \
> 
--deployer_tfstate_key: command not found
azureadm@mgmtweeudep00deploy00:~/Azure_SAP_Automated_Deployment/WORKSPACES/LANDSCAPE/DEV-WEEU-SAP01-INFRASTRUCTURE$     --keyvault "${key
_vault}"                                                                           \
> 
--keyvault: command not found
azureadm@mgmtweeudep00deploy00:~/Azure_SAP_Automated_Deployment/WORKSPACES/LANDSCAPE/DEV-WEEU-SAP01-INFRASTRUCTURE$     --storageaccountn
ame "${tfstate_storage_account}"                                                   \
> 
--storageaccountname: command not found
azureadm@mgmtweeudep00deploy00:~/Azure_SAP_Automated_Deployment/WORKSPACES/LANDSCAPE/DEV-WEEU-SAP01-INFRASTRUCTURE$     --auto-approve
