### ISSUE TITLE
[BUG] SAP HANA DB Recommended OS settings for SUSE on SUSE12 only

### ISSUE THREAD

**Issue by DaniRieker** [Azure/sap-automation#342]
**Describe the bug**
Currently the SAP HANA DB Recommended OS settings will only be applied to systems matching the condition distribution_id = 'suse12'. This settings should also be changed for otther versions (suse15 or sles_sap15 for example). 

**To reproduce**
1. Create your VMs based on SUSE15 or SLES for SAP 15
2. Run Pipeline 5 Step 2 (SAP Operating System Configuration)
3. You will find the recommended settings not applied, you can use cat /sys/kernel/mm/transparent_hugepage/enabled to check

**Expected behavior**
The recommended settings should be applied to the other versions of SUSE as well.

**Additional context**
I would recommend to just change the condition in deploy\ansible\roles-sap-os\2.10-sap-notes\tasks\main.yaml line 32 to something like - distribution_id in ['suse12', 'suse15', 'sles_sap12', 'sles_sap15']

**Comment by jhajduk-microsoft** [comment]
Will attempt to repro

**Comment by jhajduk-microsoft** [comment]
Able to reproduce
PR 392
