### ISSUE TITLE
Framework guidance and SAP Hana Multitenant support

### ISSUE THREAD

**Issue by abhisheksr01** [Azure/sap-automation#343]
**Is your feature request related to a problem? Please describe.**
Hi, 
We are currently exploring the framework to understand if we can use it to spin/migrate an SAP non-production on Premise environment to Azure cloud using Framework.

We are following the steps outlined here:
https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-tutorial

**Describe the solution you'd like**
As we continue to explore could you help us by answering the below queries:
- We feel that the framework needs customisation to meet our needs, such as, the VMs will be connected to our on-prem setup and joined to our domain with custom IP allocated to the VM utilising an existing DNS server, linking the infrastructure to an existing firewall instead of creating a firewall as part of the setup. We would like to understand what is the recommendation/best practice to adapt to this framework or if customisation of the framework is ok?
- Support for multi-tenant HANA database setup – Currently in our on-prem setup we run ECC, CRM, Gateway and Process Orchestration (PO) on a single HANA instance with multi-tenant enabled. Does this feature is supported through the configuration?
- Our SAP modules (ECC, CRM, Gateway and Process Orchestration), SCS and Application Servers use Windows Server. The Hana DB is on Linux SUSE 12 SPS4.  So if we would like to alter the VM Configurations what areas of the framework do we need to change/amend in order to achieve the above?
- Can we configure the framework to point to a media that is available in the Azure storage account rather than downloading from the marketplace (in case our required software version is not available in the SAP software marketplace)?
- Can we decouple the Infrastructure provisioning and SAP Application installation using the framework? In case the team decides to only automate the infrastructure provisioning of the framework.

**Describe alternatives you've considered**
Best practices to use the framework and probably a FAQ section with troubleshooting guidelines.

**Additional context**

**Comment by PmeshramPM** [comment]
HI @abhisheksr01 - 

My apologies for the extreme delay in replying back to this issue. This one fell through the cracks. Could you please let us know if you are still seeking the answers ?

Regards
Pankaj

**Comment by PmeshramPM** [comment]
@abhisheksr01 - I am closing this one but please feel free to raise another one in case if you have questions.
