### ISSUE TITLE
[BUG] SLES 15 SP3 - Deploy control plane - some issues in the "configure_deployer.sh.tmpl" template

### ISSUE THREAD

**Issue by amach4** [Azure/sap-automation#345]
According to my tests using PAYG SLES 15 SP3 based image for the deployer instance, the template "configure_deployer.sh.tmpl" has some issues and needs to be modified for official SLES 12/15 based Azure images.

Deploy control plane - https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-deploy-control-plane?tabs=linux#deploy-the-control-plane-1

Modified Deployer configuration file "MGMT-WEEU-DEP00-INFRASTRUCTURE.tfvars":

<snip>

\# The deployer_image defines the Virtual machine image to use, if source_image_id is specified the deployment will use the custom image provided, in this case os_type must also be specified

deployer_image = {
  "os_type"         = "Linux"
  "source_image_id" = ""
  "publisher"       = "suse"
  "offer"           = "sles-15-sp3"
  "sku"             = "gen2"
  "version"         = "latest"
}

</snip>

---

**Here the diff for the template "/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl"**

**Issue 1:**
Wrong zypper command options used

\-        sudo ${pkg_mgr} --gpg-auto-import-keys --quiet upgrade
\+        sudo ${pkg_mgr} --gpg-auto-import-keys --non-interactive patch

---

**Issue 2:**
The package "sshpass" is available in SUSE Package Hub 15 SP3 repository, this repo is not activated in the SLES 15 SP3 based images available on Azure.
The package "apt-transport-https" is not available in official SLES 15 SP3 repositories.

\-        apt-transport-https
\+#        apt-transport-https

\-        sshpass
\+#        sshpass

---

**Issue 3:**
Command not needed with SLES 12/15 based deployer image
 
\-    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash > /dev/null
\+# curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash > /dev/null

---

**Issue 4:**
Repository providing the "snapd" package is not available

\-    sudo snap install dotnet-sdk --classic --channel=3.1
\-    sudo snap alias dotnet-sdk.dotnet dotnet
\+#    sudo snap install dotnet-sdk --classic --channel=3.1
\+#    sudo snap alias dotnet-sdk.dotnet dotnet

---

NOTE: This is what was used to successfully deploy the control plane, using PAYG SLES 15 SP3 based deployer image.

**Comment by andreas-mach** [comment]
renamed "configure_deployer.sh.tmpl" template example:
[configure_deployer.sh.tmpl.txt](https://github.com/Azure/sap-automation/files/10020557/configure_deployer.sh.tmpl.txt)
