### ISSUE TITLE
[BUG]  Issue with conifguration_menu.sh and Option 3.

### ISSUE THREAD

**Issue by philnandreoli** [Azure/sap-automation#35]
When following the steps in the hands on lab and when I get to the part of the section where I have to execute configuration_menu.sh it errors on menu item 3.  I believe that there is a step missing in the hands on lab to run the generate_bom.sh before executing step 3 of BOM processing.  

Here is the error message when I execute option 3 of the configuration_menu.sh

Please select playbook: 3
You selected (3) BOM Processing

PLAY [localhost] ***************************************************************************************************************************************************************************************************************************************************************************************
Thursday 13 January 2022  13:56:02 +0000 (0:00:00.020)       0:00:00.020 ****** 

TASK [Load the SAP parameters] *************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:02 +0000 (0:00:00.040)       0:00:00.060 ****** 

TASK [Construct SSH key secret name] *******************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:02 +0000 (0:00:00.037)       0:00:00.097 ****** 

TASK [Retrieve SSH Key secret details] *****************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:03 +0000 (0:00:00.920)       0:00:01.018 ****** 

TASK [Extract SSH Key content from secret details] *****************************************************************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:03 +0000 (0:00:00.039)       0:00:01.057 ****** 

TASK [Determine SSH key file name] *********************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:03 +0000 (0:00:00.039)       0:00:01.096 ****** 

TASK [Determine SSH key file path] *********************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:03 +0000 (0:00:00.039)       0:00:01.135 ****** 

TASK [Write out SSH Key content as sshkey file] ********************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Thursday 13 January 2022  13:56:04 +0000 (0:00:00.542)       0:00:01.678 ****** 
=============================================================================== 
Retrieve SSH Key secret details ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.92s
Write out SSH Key content as sshkey file -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.54s
Load the SAP parameters ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
Extract SSH Key content from secret details ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
Determine SSH key file path --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
Determine SSH key file name --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
Construct SSH key secret name ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s

PLAY [Get Storage account details from KeyVault] *******************************************************************************************************************************************************************************************************************************************************
Thursday 13 January 2022  13:56:04 +0000 (0:00:00.034)       0:00:01.712 ****** 

TASK [Set 'sa' tier] ***********************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:04 +0000 (0:00:00.037)       0:00:01.749 ****** 

TASK [Remove .step3 flag] ******************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:04 +0000 (0:00:00.333)       0:00:02.083 ****** 
Thursday 13 January 2022  13:56:04 +0000 (0:00:00.043)       0:00:02.126 ****** 
Thursday 13 January 2022  13:56:04 +0000 (0:00:00.035)       0:00:02.162 ****** 

TASK [roles-misc/0.3.sap-installation-media-storage-details : Workload Keyvault name] ******************************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:04 +0000 (0:00:00.037)       0:00:02.199 ****** 

TASK [roles-misc/0.3.sap-installation-media-storage-details : Get Deployer Keyvault name from keyvault] ************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:05 +0000 (0:00:00.802)       0:00:03.002 ****** 
Thursday 13 January 2022  13:56:05 +0000 (0:00:00.035)       0:00:03.037 ****** 

TASK [roles-misc/0.3.sap-installation-media-storage-details : Save Deployer Keyvault name] *************************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:05 +0000 (0:00:00.040)       0:00:03.078 ****** 
Thursday 13 January 2022  13:56:05 +0000 (0:00:00.037)       0:00:03.116 ****** 

TASK [roles-misc/0.3.sap-installation-media-storage-details : Extract SAP Binaries Storage Account information] ****************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:06 +0000 (0:00:00.801)       0:00:03.917 ****** 

TASK [roles-misc/0.3.sap-installation-media-storage-details : Save SAP Binaries Storage Account information] *******************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:06 +0000 (0:00:00.037)       0:00:03.955 ****** 
Thursday 13 January 2022  13:56:06 +0000 (0:00:00.036)       0:00:03.992 ****** 

TASK [roles-misc/0.3.sap-installation-media-storage-details : Extract SAP Binaries Storage Account SAS] ************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:07 +0000 (0:00:00.791)       0:00:04.783 ****** 

TASK [roles-misc/0.3.sap-installation-media-storage-details : Extract SAP Binaries Storage Account SAS] ************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 13 January 2022  13:56:07 +0000 (0:00:00.038)       0:00:04.822 ****** 

PLAY [BOM Processing] **********************************************************************************************************************************************************************************************************************************************************************************
Thursday 13 January 2022  13:56:07 +0000 (0:00:00.056)       0:00:04.878 ****** 

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************************************************************************
ok: [x00scs00le3f]
Thursday 13 January 2022  13:56:09 +0000 (0:00:01.576)       0:00:06.454 ****** 

TASK [Set facts] ***************************************************************************************************************************************************************************************************************************************************************************************
ok: [x00scs00le3f]
Thursday 13 January 2022  13:56:09 +0000 (0:00:00.031)       0:00:06.486 ****** 
Thursday 13 January 2022  13:56:09 +0000 (0:00:00.033)       0:00:06.519 ****** 

TASK [roles-sap/3.3-bom-processing : Check required variables are present and not empty] ***************************************************************************************************************************************************************************************************************
ok: [x00scs00le3f] => {
    "changed": false,
    "msg": "All assertions passed"
}
Thursday 13 January 2022  13:56:09 +0000 (0:00:00.038)       0:00:06.558 ****** 

TASK [roles-sap/3.3-bom-processing : Check required variables are present and not empty (bom)] *********************************************************************************************************************************************************************************************************
fatal: [x00scs00le3f]: FAILED! => {
    "assertion": "bom_base_name | type_debug != 'NoneType'",
    "changed": false,
    "evaluated_to": false,
    "msg": "Please ensure that the BOM details are provided"
}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=16   changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
x00scs00le3f               : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Thursday 13 January 2022  13:56:09 +0000 (0:00:00.025)       0:00:06.583 ****** 
=============================================================================== 
Gathering Facts --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.58s
Retrieve SSH Key secret details ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.92s
roles-misc/0.3.sap-installation-media-storage-details : Get Deployer Keyvault name from keyvault ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.80s
roles-misc/0.3.sap-installation-media-storage-details : Extract SAP Binaries Storage Account information ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.80s
roles-misc/0.3.sap-installation-media-storage-details : Extract SAP Binaries Storage Account SAS ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.79s
Write out SSH Key content as sshkey file -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.54s
Remove .step3 flag ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.33s
roles-misc/0.3.sap-installation-media-storage-details : Debug, SAS Token ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.06s
Include 0.3.sap-installation-media-storage-details role ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
roles-misc/0.3.sap-installation-media-storage-details : Save Deployer Keyvault name ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
Load the SAP parameters ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
Extract SSH Key content from secret details ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
Determine SSH key file path --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
Determine SSH key file name --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
roles-misc/0.3.sap-installation-media-storage-details : Extract SAP Binaries Storage Account SAS ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.04s
roles-sap/3.3-bom-processing : Check required variables are present and not empty --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
roles-misc/0.3.sap-installation-media-storage-details : Debug, Deployer Keyvault ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
Set 'sa' tier ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
roles-misc/0.3.sap-installation-media-storage-details : Save SAP Binaries Storage Account information ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
roles-misc/0.3.sap-installation-media-storage-details : Workload Keyvault name ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.04s

**Comment by hdamecharla** [comment]
Hi @philnandreoli , thank you for raising the bug. 

The steps for acquiring the BOM components are described in the [get-sap-software-using-the-bill-of-materials-bom](https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-tutorial#get-sap-software-using-the-bill-of-materials-bom) section of the hands-on-lab. 

The `sap-parameters.yaml` file needs to have the `bom_base_name:` parameter defined in it for the playbook to know which BOM is to be processed. The entry is populated based on the BOM name provided in the system deployment [tfvars](https://github.com/Azure/sap-automation/blob/main/training-materials/WORKSPACES/SYSTEM/DEV-EAUS-SAP01-X00/DEV-EAUS-SAP01-X00.tfvars#L64) or can be defined manually in the file itself.
