### ISSUE TITLE
{Bug} Azuredevops pipelines resets the Key vault(secrets) access Policies

### ISSUE THREAD

**Issue by prashanthbv12** [Azure/sap-automation#350]
Hello,

While we are running the workload zone via azure devops pipeline , the Pipeline is resetting the permissions back to "get" and "List" and it is giving error the SPN do not have access to the control plane Keyvault.
For now we have hard coded to set the permissions and this needs to be fixed in future releases

Thanks,
Prashanth

**Comment by enterprise-1701-d** [comment]
That is only happening when you don't have a separate SPN for the control plane and the workload zone.

**Comment by PankajMeshramCSA** [comment]
@prashanthbv12 - This has been fixed with our recent release 3.6 , could you please check and confirm?

**Comment by hdamecharla** [comment]
Closing this.
