### ISSUE TITLE
SCS Installation fails with the below error when we used the HA for SCS with oracle DB

### ISSUE THREAD

**Issue by phaniteluguti** [Azure/sap-automation#351]
TASK [roles-sap/3.3.1-bom-utility : 3.3.1 BoM Template processing: - Set Python version sles_sap15] ***
ok: [or1scs00l9a8]

TASK [roles-sap/3.3.1-bom-utility : 3.3.1 BoM Template processing: Create hidden directory] ***
ok: [or1scs00l9a8]

TASK [roles-sap/3.3.1-bom-utility : 3.3.1 BoM Template processing: Ensure download directory exists] ***
ok: [or1scs00l9a8]

TASK [roles-sap/3.3.1-bom-utility : 3.3.1 BoM Template processing: ORACLE_19_00_v0002ms Download: ORACLE_19_00_v0002ms-scsha-inifile-param.j2 from the storage account] ***
ok: [or1scs00l9a8 -> localhost]

TASK [roles-sap/3.3.1-bom-utility : 3.3.1 BoM Template processing: Create ini file ORACLE_19_00_v0002ms-scsha-or1scs00l9a8.params from ORACLE_19_00_v0002ms-scsha-inifile-param.j2] ***
ok: [or1scs00l9a8]

TASK [roles-sap/5.0.1-scs-ha-install : SCS HA Install: install variables] ******
fatal: [or1scs00l9a8]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'scs_ha'\n\nThe error appears to be in '/home/azureadm/agent/_work2/6/s/deploy/ansible/roles-sap/5.0.1-scs-ha-install/tasks/main.yaml': line 95, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name:                            \"SCS HA Install: install variables\"\n      ^ here\nThis one looks easy to fix. It seems that there is a value started\nwith a quote, and the YAML parser is expecting to see the line ended\nwith the same kind of quote. For instance:\n\n    when: \"ok\" in result.stdout\n\nCould be written as:\n\n   when: '\"ok\" in result.stdout'\n\nOr equivalently:\n\n   when: \"'ok' in result.stdout\"\n"}

**Comment by hdamecharla** [comment]
Hi @msftvapolasa , can you take a look at this please?
