### ISSUE TITLE
[BUG] Secondary IP not reachable 

### ISSUE THREAD

**Issue by phaniteluguti** [Azure/sap-automation#352]
**Describe the bug**
When using the secondary IP/virtual hostname, PING to the secondary IP is failing and sapinst also fails to install the SCS on SLES 15 SP3

**To reproduce**
SCS installation pipeline execution fails with virtual hostname(secondary IP) not reachable.

**Expected behavior**
the Ansible scripts missed to set the CLOUD_NETCONFIG_MANAGE to 'yes' in /etc/sysconfig/network/ifcfg-eth0. once the value is set to yes the ping is successful to secondary IP and installation completed.

**Additional context**
May be need to fix in the ansible role-os/networking or the other script

**Comment by hdamecharla** [comment]
Hi @phaniteluguti , thank you for raising the bug. 

Could you let us know the installation scenario, i.e. Standard, Distributed or Highly Available, please?

**Comment by phaniteluguti** [comment]
Hi Hemanth,

I started the HA installation for SCS and oracle DB with Azure Devops pipeline. But faced an issue with SCSHA/ERSHA installation as mentioned in the BUG 352. So disabled the SCS HA in the parameter file to proceed with the normal SCS installation and faced this issue, that SWPM not able to reach this SAP virtual hostname(secondary IP), I had to make the above change in the /etc/sysconfig/netwrok/ifcfg-eth0 to proceed with the SCS installation and complete it successfully.

APP/SCS - on SLES 15 SP03
oracle DB / oracle observer - on Oracle Linux 8.2

Managed to complete the SAP installation with Devops pipeline. Faced two more issues with 'sidadm' user ownership assignment and the 'spfile' creation in the oracle data guard setup, I will raise separate issues for  those two. 

Best Regards,
Phani

**Comment by RustyNails8** [comment]
Hi @hdamecharla @phaniteluguti ,

I was able to identify the issue to 3 possible files:

1. [deploy\ansible\roles-os\1.17-generic-pacemaker\tasks\1.17.2-provision.yml](deploy\ansible\roles-os\1.17-generic-pacemaker\tasks\1.17.2-provision.yml)
2. [deploy\ansible\roles-os\1.17-generic-pacemaker\tasks\1.17.2.0-cluster-Suse.yml](deploy\ansible\roles-os\1.17-generic-pacemaker\tasks\1.17.2.0-cluster-Suse.yml)

The above 2 files :point_up_2: are setting CLOUD_NETCONFIG_MANAGE to no.
Not fully sure if this can be removed [I think not].

But perhaps here it can be added in this file :point_down:

3. [deploy\ansible\roles-os\1.10-networking\tasks.yml](deploy\ansible\roles-os\1.10-networking\tasks.yml)

```
64      ONBOOT=yes
65     IPADDR="{{ secondary_ip }}"
66      NETMASK=255.255.255.0
67+      CLOUD_NETCONFIG_MANAGE='yes'
68    mode:                              755
69  register:                            definition_made
70  when:
```
