### ISSUE TITLE
[BUG] - Missing assignee in Azure DevOps Script

### ISSUE THREAD

**Issue by shoootyou** [Azure/sap-automation#389]
**Describe the bug**

**To reproduce**
1. Use the script on [Automation Configure Website](https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-configure-devops?tabs=windows#configure-azure-devops-services-for-the-sap-on-azure-deployment-automation-framework)
2. Instance project: TSO (for testing purpose)
3. Do you want to create a new Application registration (needed for the Web Application) y/n? y
4. Do you want to create a new Service Principal for the Control plane y/n?: y
5. Do you want to create a new Service Principal for the Workload zone y/n?: y
6.  < Ask for authorization >
7. Shows the following:
```
Using Organization: https://dev.azure.com/XXXXXXX
Using Control plane code: MGMT
Using Workload zone code: DEV
Installing the DevOps extensions
Creating the project:  SAP Deployment Automation Framework
Importing the content from GitHub
```
8. You can optionally import the Terraform and Ansible code from GitHub into Azure DevOps, however, this should only be done if you cannot access github from the Azure DevOps agent or if you intend to customize the code. Do you want to run the code from GitHub y/n?: y
9. Open the page of Service Connections on Azure DevOps and Authorize with my Github personal account and write the Service Connections' name. In the security section, mark "Grant access permission to all pipelines"
10. Do you want to provide the S user details y/n?: n
11.  Shows the following error multiples times:
```
Read more about the command in reference docs
argument --assignee: expected one argument

Examples from AI knowledge base:
az role assignment create --assignee sp_name --role a_role
Create role assignment for an assignee.

az role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id
Create a new role assignment for a user, group, or service principal. (autogenerated)
```

**Expected behavior**
Runn without errors.

**Additional context**
* Azure-CLI version: 2.43.0
* PowerShell Version:
```
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KimForss** [comment]
Hi @shoootyou 

Sorry for the issues you are having. I wonder can it be that your account does not have User Access Administration permissions on the target subscription(s)? 

That would explain the error.

Can you send me an email on kimforss@microsoft.com and I can provide you with a more verbose version of the setup script so that we can better identify the root cause.
