### ISSUE TITLE
[BUG] incorrect system deployment type specified 

### ISSUE THREAD

**Issue by cjpark-sapcsa** [Azure/sap-automation#403]
HI Team,

I am following the deployment hands-on lab and the Apply finished the below error. 

Anyone seen this before? 

B. Rgds

ChanJin  

 calling installer.sh with parameters:  --parameterfile MGMT-WEEU-DEP00-INFRASTRUCTURE.tfvars --storageaccountname  --type sap_deployer  --auto-approve  
#########################################################################################
#                                                                                       #
#   Incorrect system deployment type specified:                                         #
#                                                                                       #
#     Valid options are:                                                                #
#       sap_deployer                                                                    #
#       sap_library                                                                     #
#       sap_landscape                                                                   #
#       sap_system                                                                      #
#                         

**To reproduce**
1. Go to  :  https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-tutorial 
Create the Deployer and the SAP Library and add the Service Principal details to the deployment key vault.

#######################################################################################
#                                                                                       #
#                              Setting the secrets                                      #
#                                                                                       #
#########################################################################################

#########################################################################################
#                                                                                       #
#                           Bootstrapping the library                                   #
#                                                                                       #
#########################################################################################

 -p MGMT-WEEU-SAP_LIBRARY.tfvars -d DEPLOYER/MGMT-WEEU-DEP00-INFRASTRUCTURE  --auto-approve

#########################################################################################
#                                                                                       #
#                    Directory does not exist:  DEPLOYER/MGMT-WEEU-DEP00-INFRASTRUCTURE #
#                                                                                       #
#########################################################################################

Error: Backend initialization required, please run "terraform init"

Reason: Initial configuration of the requested backend "local"

The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.

f the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.
incorrect usage: [Required] --value VALUE | --file PATH
##vso[task.setprogress value=60;]Progress Indicator
##vso[task.setprogress value=80;]Progress Indicator

#########################################################################################
#                                                                                       #
#                           Migrating the deployer state                                #
#                                                                                       #
#########################################################################################

 calling installer.sh with parameters:  --parameterfile MGMT-WEEU-DEP00-INFRASTRUCTURE.tfvars --storageaccountname  --type sap_deployer  --auto-approve  
#########################################################################################
#                                                                                       #
#   Incorrect system deployment type specified:                                         #
#                                                                                       #
#     Valid options are:                                                                #
#       sap_deployer                                                                    #
#       sap_library                                                                     #
#       sap_landscape                                                                   #
#       sap_system                                                                      #
#                                                                                       #
#########################################################################################

**Comment by PankajMeshramCSA** [comment]
@cjpark-sapcsa - could you please let me know whether you are using DevOps or scripts?

**Comment by cjpark-sapcsa** [comment]
HI @PankajMeshramCSA     I am using https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-tutorial  script. 

B. Rgds

CJ

**Comment by cjpark-sapcsa** [comment]
Hi team, 

Fix the error with change of script 


  ${DEPLOYMENT_REPO_PAT****H}/deploy/scripts/prepare_region.sh****                                                                                       \
        --deployer_parameter_file DEPLOYER/${env_code}-${region_code}-DEP00-INFRASTRUCTURE/${env_code}-${region_code}-DEP00-INFRASTRUCTURE.tfvars  \
        --library_parameter_file LIBRARY/${env_code}-${region_code}-SAP_LIBRARY/${env_code}-${region_code}-SAP_LIBRARY.tfvars                      \
        --subscription "${subscriptionId}"                                                                                                         \
        --spn_id "${spn_id}"                                                                                                                       \
        --spn_secret "${spn_secret}"                                                                                                               \
        --tenant_id "${tenant_id}"                                                                                                                 \
        --auto-approve
