### ISSUE TITLE
[Feature] HANA performance testing with HCMT

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#41]
**Is your feature request related to a problem? Please describe.**
Please add a playbook and pipeline to allow automatic HANA performance testing with HCMT

**Describe the solution you'd like**
- Add the HCMT to the BOM for binary upload to storage account
- Add an ansible playbook for the execution
- Add a pipeline to handle the execution from DevOps

**Describe alternatives you've considered**
- Manual execution is no fun ;-)

**Additional context**
none

**Comment by KimForss** [comment]
Code added
