### ISSUE TITLE
Error While running SAP configuration : Secondary IP Issue

### ISSUE THREAD

**Issue by prashanthbv12** [Azure/sap-automation#413]
When we have secondary IP attached to same nic, curl command to Microsoft public IP with seconday IP does not work and hence the VM agents stop loading.
Below is the error from pipeline

TASK [roles-os/1.10-networking : 1.10 Networking - Get the IP information from instance meta data service] ***
fatal: [z127812d01lsxeascs]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

**Comment by hdamecharla** [comment]
Hi @prashanthbv12 , we are working on this.
