### ISSUE TITLE
[BUG] : Pipeline error while running SAP configuration 

### ISSUE THREAD

**Issue by prashanthbv12** [Azure/sap-automation#415]
Hello,

While running SAP configuration it is giving below error.
Looks like it is trying to search for secondary nic although we have used primary IP and secodary IP in the same nic

For each host, loop over all the network interfaces except 'lo' (localhost)\n 3) Check for ipv4 configuration the interface\n 4) If the interface is eth0\n True : This is the primary NIC and IP for the host\n False: This is a Secondary NIC with primary IP for this NIC\n 5) If the NIC has secondary IP adresses assigned loop over them and\n insert comment for unhandled configuration\n\nExamples:\n hosts file

**Comment by hdamecharla** [comment]
Hi @prashanthbv12, thanks for raising the bug. We will keep you posted on the resolution.

**Comment by KimForss** [comment]
Hi, This will be closed with release 3.8
