### ISSUE TITLE
[BUG] While installing the S4HANA 2022

### ISSUE THREAD

**Issue by prashanthbv12** [Azure/sap-automation#431]
ERROR      2023-03-07 12:58:22.212 (root/sapinst) (startInstallation) [iaxxbjsmod.cpp:83] id=nw.processError errno=CJS-30023
Process call '/usr/sap/BLD/SYS/exe/uc/linuxx86_64/sapcpe stdoutput pf=/usr/sap/BLD/SYS/profile/BLD_ASCS00_sapbldascs list:/usr/sap/BLD/SYS/exe/uc/linuxx86_64/scs.lst' exits with error code 1. For details see log file(s) sapcpe_sapinst.log.

**Comment by KimForss** [comment]
Thanks, this will be closed with Release 3.8
