### ISSUE TITLE
[BUG] Path to HDB script is hardcoded with HANA instance-number 00

### ISSUE THREAD

**Issue by crweller** [Azure/sap-automation#432]
**Describe the bug**

There is a path to the HDB script hardcoded.
In the playbook deploy\ansible\roles-db\4.0.1-hdb-hsr\tasks\4.0.1.1-set_runtime_path_facts.yml ,line 52, the HDB script ist used to check the version. 
The HDB script is reference with this path:  /hana/shared/{{ db_sid | upper }}/HDB00/HDB

This leads to a failing play "HANA HSR: - capture the Hana DB version", if you install HANA with a different instance number than 00. 

**To reproduce**

Install HANA in a high availability environment with a instance number != 00 by setting 'hdb_instance_number' in sap-parameters.yaml.
Setup the HANA Systemreplication.

**Expected behavior**

Play is running the HDB script and results are available for further assertions.

**Additional context**

To correct the issue, I just replaced HDB00 with HDB{{ hdb_instance_number }}.

**Comment by KimForss** [comment]
Thanks, this will be fixed in the upcoming 3.8 release
