### ISSUE TITLE
Getting Product ID for BOM preparation is still very manual

### ISSUE THREAD

**Issue by prashanthbv12** [Azure/sap-automation#444]
Hello,

Thanks for various improvements in the product and we were able to deploy few applications successfully via SDAF.
However when deploying certain applications like ERP 7 and other older versions getting the product ID to prepare BOM is very difficult. We have to try installing the Application via swpm and we have to get the product id from the catalog. And this ID has to be given in the yaml file. There is no automatic way where the tool detects the product IDs.
And we are installing applications which needs older version of SWPM is not supported (we faced this while installing ERP 7) so we decided to manually install the software using older version of SWPM. This has to be take care as well.

Thanks

**Comment by prasroy** [comment]
@prashanthbv12 - Thanks for proving the feedback. We really appreciate that. However the installation method we are following here is a standard Non-Observer SAP installation mode by using a parameter file through SWPM. SAP has a detail guidance how to prepare the parameter file to use this installation mode. Please take a look at here
For SWPM 2.0
https://help.sap.com/docs/SLTOOLSET/39c32e9783f6439e871410848f61544c/3e7738abf8674ed7a6448d8c04fa5de7.html?version=CURRENT_VERSION_SWPM20&locale=en-US
For SWPM 1.0
https://help.sap.com/docs/SLTOOLSET/910828cec5d14d6685da380aec1dc4ae/3e7738abf8674ed7a6448d8c04fa5de7.html?version=CURRENT_VERSION&locale=en-US
To know the product ID of the relevant SAP component you need to run SWPM and follow the instructions on the screens by entering all parameter values and finally stop after the parameter summery screen.
Now find the input parameter file named “inifile.params” in the installation directory and then you can check product ids at the header of the generated input parameter file.
Hope this helps!

**Comment by hdamecharla** [comment]
This is not a bug. We have tagged it as an enhancement. 

We do have plans to simplify the BOM creation process and this is being planned for a future release.
