### ISSUE TITLE
Ability to define a custom Windows Cluster name and cluster object names

### ISSUE THREAD

**Issue by jkirkmannz** [Azure/sap-automation#467]
**Is your feature request related to a problem? Please describe.**
The feature is to cater for an environment where SDAF is used to set up a new SAP landscape, but existing Windows clusters exist with the same naming standard - <SID>scs<InstanceNumber>cl. Also the DNS name for the DB HA entry.

**Describe the solution you'd like**
Ability to define the name of the cluster and cluster objects and DB DNS entry

**Describe alternatives you've considered**
There is no alternative, as the names already exist in AD/DNS, and are in use by existing production systems, it is not possible to re-use them.

**Additional context**
The code below implements a standard naming convention which has already been used in the existing SAP landscape:
- name:                                "5.6 SCSERS - Set the SCS Virtual Instance hostname"
  ansible.builtin.set_fact:
    scs_virtual_hostname:              "{{ sap_sid | lower }}scs{{ scs_instance_number }}cl1"
  when:
    - scs_high_availability

- name:                                "5.6 SCSERS - Set the ERS Virtual Instance hostname"
  ansible.builtin.set_fact:
    ers_virtual_hostname:              "{{ sap_sid | lower }}ers{{ ers_instance_number }}cl2"
  when:
    - scs_high_availability

**Comment by hdamecharla** [comment]
We can now add these via the configuration_settings block to the system tfvars file. Which will add them to the sap-parameters.yaml.

```terraform
# configuration_settings is a dictionary containing values that will be persisted in sap-parameters.yaml
configuration_settings = {
  ora_release = "19",
  ora_version = "19.0.0",
  oracle_sbp_patch = "SAP19P_2305-70004508.ZIP",
  oraclegrid_sbp_patch = "SGR19P_2308-70004550.ZIP",
}
```
