### ISSUE TITLE
[BUG] LOCATION_IN_FILENAME for Japan is invalid in Workload zone pipeline

### ISSUE THREAD

**Issue by ugaki-fj** [Azure/sap-automation#470]
Hello

I found spelling errors in [deploy/pipelines/02-sap-workload-zone.yaml](https://github.com/Azure/sap-automation/blob/main/deploy/pipelines/02-sap-workload-zone.yaml)

There are errors in LOCATION_IN_FILENAME for Japan.
`    "JAEA") LOCATION_IN_FILENAME="japaneastst" ;;`
`    "JAWE") LOCATION_IN_FILENAME="japanwestst" ;;`

The final "st" are unnecessary. The correct value are as follows.
`    "JAEA") LOCATION_IN_FILENAME="japaneast" ;;`
`    "JAWE") LOCATION_IN_FILENAME="japanwest" ;;`

Thank you

**Comment by jhajduk-microsoft** [comment]
waiting for PR to be approved: https://github.com/Azure/sap-automation/pull/471
