### ISSUE TITLE
[BUG] error happens when Valication was launched from configuration_menu.sh menu

### ISSUE THREAD

**Issue by nrts** [Azure/sap-automation#472]
**Describe the bug**
The error happens when Validation was launched from configuration_menu.sh menu.

**To reproduce**
1. Select Validation menu from configuration_menu.sh to install SAP instance
2. See error message:
TASK [0.0 Validations - Save the Json data to a Variable as a Fact] 
ok: [localhost]
[WARNING]: an unexpected error occurred during Jinja2 environment setup: unable to locate collection community.general

TASK [0.0 Validations - Extract details] 
fatal: [localhost]: FAILED! => {"msg": "template error while templating string: unable to locate collection community.general. String: {{ json_azure_data | json_query('compute.subscriptionId') }}"}

**Expected behavior**
Successfully finish validation menu.

**Additional context**
When I start the validation playbook directly, the validation process finished successfuly.

**Comment by KimForss** [comment]
This is fixed in the latest release, the problem was a missing ':' in the PATH environment variable
