### ISSUE TITLE
Move DBload schema backup location to /hana/backup

### ISSUE THREAD

**Issue by shekharsorot** [Azure/sap-automation#49]
[Enhancement]

[Observation]
Current schema backup directory for S4HANA and NetWeaver in DBLoad stage is set to /usr/sap/<SID>/<SID><DBInstance>backup/data/DB_HDB.
During installation, this schema export crosses 77GB for S4CORE and ~40GB for NetWeaver.
For Small systems where /usr/sap is provided as a 1 x P6 ( as per MSFT documenation ), this will result in installation failure.
Resuming installation requires manually dropping the Schema 'SAPHANADB' and restarting setup.

[Primary Fix]
Change the "NW_Recovery_Install_HDB.extractLocation" to  /hana/backup in DBLoad template

[Alternative Fix]
/hana/shared can be used as well where this volume is minimum of 1.25x the  VM Memory size.

**Comment by KimForss** [comment]
Hi, sorry for the late response - this is fixed for HANA - and will be fixed in the next PR
