### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dannyssc-ict** [Azure/sap-automation#492]
**Describe the bug**
deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/storage_accounts.tf
line 38
enable_https_traffic_only       = false **change to ** enable_https_traffic_only       = true **in main**

**Additional context**
Our company has a strict policy to enfore TLS1.2 and HTTPS ONLY.

**Comment by dannyssc-ict** [comment]
or change value **false/true** in variable which can be passed by terrafrom vars file

**Comment by hdamecharla** [comment]
The Terraform code you mentioned relates to a storage account used for an Azure Files NFS share. It's important to understand that, currently, Azure doesn't offer support for encryption in transit for this particular type of share. If you decide to keep this option enabled, it may prevent you from successfully mounting the NFS share onto your virtual machine, resulting in timeout issues during the mounting process.
 

To help with this, we've implemented a private endpoint for added security. This means the resource is accessible only within the boundaries of the associated virtual network.

For a more in-depth understanding of Azure Files NFS protocol and its compatibility with various Azure storage features, we recommend taking a look at [the documentation available here](https://learn.microsoft.com/en-us/azure/storage/files/files-nfs-protocol#support-for-azure-storage-features).
