### ISSUE TITLE
Software Acquisition pipeline errors if no checksum defined for a package.

### ISSUE THREAD

**Issue by jkirkmannz** [Azure/sap-automation#529]
When running the Software Acquisition pipeline to download s/w for a BoM, if packages do not have a checksum defined an error is returned.

**To reproduce**
1. Run the Software Acquisition Pipeline
2. Select "NW750SPS25_v0001ms.yaml" 
3. See error: 
_TASK [roles-sap/0.1-bom-validator : BOM: Verify Files] *************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '(bom_media_entry.checksum is not defined and create_checksums is defined) or (bom_media_entry.checksum | bool)' failed. The error was: error while evaluating conditional ((bom_media_entry.checksum is not defined and create_checksums is defined) or (bom_media_entry.checksum | bool)): 'dict object' has no attribute 'checksum'. 'dict object' has no attribute 'checksum'\n\nThe error appears to be in '/home/azureadm/agent/_work/4/s/sap-automation/deploy/ansible/roles-sap/0.1-bom-validator/tasks/bom_download.yaml': line 235, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n#\n        - name:                        \"BOM: Verify Files\"\n          ^ here\nThis one looks easy to fix. It seems that there is a value started\nwith a quote, and the YAML parser is expecting to see the line ended\nwith the same kind of quote. For instance:\n\n    when: \"ok\" in result.stdout\n\nCould be written as:\n\n   when: '\"ok\" in result.stdout'\n\nOr equivalently:\n\n   when: \"'ok' in result.stdout\"\n"}_

**Expected behavior**
The software should download without error despite no checksums being added - this used to be the case maybe 6-8 months ago.

**Additional context**
If checksums are added to the yaml file then files are downloaded, but the checksums are not populated automatically and with hundreds of files adding them manually is time-consuming.

**Comment by miked1903** [comment]
+1 for same issue with NW750SPS25_v000. S41909SPS03_v0011ms  appears to be working.

**Comment by hdamecharla** [comment]
Hi @jkirkmannz @miked1903, apologies for the delayed response. 

We may have identified the root cause for this and are testing the code fix. We will push an update soon to the experimental branch. Will keep you posted on when the code lands. 

Thank you, for your patience.
