### ISSUE TITLE
ACSS - step is failing in the new version

### ISSUE THREAD

**Issue by cdornele** [Azure/sap-automation#601]
Hey there,

The new Ansible steps for ACSS registration it is not working. I am running S4HANA FP 2022 and HANA v2 77. 
PAS and SCS are running in the same VM.

I am getting errors during the az extensions and the validations in the lines:

TASK [roles-misc/0.5-ACSS-registration : 0.5.1 acss registration: - Set variables from Azure IMDS] ***
fatal: [corps4xap1 -> localhost]: FAILED! => {"changed": false, "cmd": "'az extension add --name workloads --yes || exit 1'", "msg": "[Errno 2] No such file or directory: b'az extension add --name workloads --yes || exit 1'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

I've added manually and commented this part of code in my own repo, however, after this task, I am getting a new error in this step:

TASK [roles-misc/0.5-ACSS-registration : Create [ACSS] virtual instance] *******
fatal: [corps4xap1]: FAILED! => {"msg": "The conditional check 'cluster_group_location.stdout != ansible_hostname' failed. The error was: error while evaluating conditional (cluster_group_location.stdout != ansible_hostname): 'dict object' has no attribute 'stdout'. 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '/home/azureadm/agent/_work/8/s/sap-automation/deploy/ansible/roles-misc/0.5-ACSS-registration/tasks/main.yaml': line 115, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name:                            \"Create [ACSS] virtual instance\"\n      ^ here\n"}

**Comment by hdamecharla** [comment]
Hi @cdornele , thank you for raising the bug.

As quick reproduction, on the deployer VM are you able to run the following commands:

1. `az extension list`
2. `az extension add --name workloads --yes --verbose`

Please let me know if these run successfully.
