### ISSUE TITLE
Enable cross_tenant_replication to be set to false for Storage Account deployment.

### ISSUE THREAD

**Issue by jkirkmannz** [Azure/sap-automation#610]
**Is your feature request related to a problem? Please describe.**
A company has an Azure Policy that prohibits Storage Accounts being created where Cross Tenant Replication is enabled. In the Azure Portal it is disabled by default, in azurerm_storage_account it is enabled by default. SDAF doesn't provide a mechanism to set one way or the other.

**Describe the solution you'd like**
Add a variable to the deployer/library TFVARS file which can be set to true or false. Use this variable with the "cross_tenant_replication_enabled" argument in all azurerm_storage_account blocks. 

**Describe alternatives you've considered**
Precreate all storage accounts from the Azure Portal and use the arm_id in the configuration file, or update the code manually to add the option.

**Additional context**
![image](https://github.com/user-attachments/assets/945ee77a-df3e-4d4a-863e-fe64044dba9a)

resource "azurerm_storage_account" "deployer" {
  count                                = length(var.deployer.deployer_diagnostics_account_arm_id) > 0 ? 0 : 1
  name                                 = local.storageaccount_names
  resource_group_name                  = local.resource_group_exists ? data.azurerm_resource_group.deployer[0].name : azurerm_resource_group.deployer[0].name
  location                             = local.resource_group_exists ? data.azurerm_resource_group.deployer[0].location : azurerm_resource_group.deployer[0].location
  account_replication_type             = "LRS"
  account_tier                         = "Standard"
  enable_https_traffic_only            = local.enable_secure_transfer
  min_tls_version                      = "TLS1_2"
  allow_nested_items_to_be_public      = false
  **cross_tenant_replication_enabled     = false**
  shared_access_key_enabled            = var.deployer.shared_access_key_enabled

**Comment by devanshjainms** [comment]
Hi @jkirkmannz , thank you for reaching out. We would consider this in the future releases. In the meantime, please explore and use alternative solutions to address this requirement.
