### ISSUE TITLE
Use SUSE/Red Hat as default deployer

### ISSUE THREAD

**Issue by Klaas-** [Azure/sap-automation#63]
**Is your feature request related to a problem? Please describe.**
This role rolls out sles or rhel VMs for SAP workloads, I think it would be a good idea to drop the default of another Linux vendor for the deployer VM.

**Describe the solution you'd like**
Use RHEL / sles for deployer VM

**Comment by KimForss** [comment]
Hi, the deployer distro is configurable, see : https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-configure-control-plane

**Comment by Klaas-** [comment]
Hi, yes I saw it's configurable -- I'm saying to change the default.

**Comment by KimForss** [comment]
The question then would be which default to choose :)
