### ISSUE TITLE
Authentication error, please check the SAS token during binary download

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#7]
**Describe the bug**
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Authentication error, please check the SAS token"}

**To reproduce**
Deploy region, library, workload zone and then download the binaries. 
The error occurs during the ansible pipeline run playbook_bom_downloader.yaml

**Expected behavior**
A valid SAS token is available in the keyvault

**Additional context**
none

**Comment by enterprise-1701-d** [comment]
I was able to find a workaround by executing the update_sas_token.sh manually and providing the 3 variables inkl. the fist SAS-key of the storage account

azureadm@mgmtweeudep00deploy00:~/Azure_SAP_Automated_Deployment/WORKSPACES/BOMS$ ~/Azure_SAP_Automated_Deployment/sap-automation/deploy/scripts/update_sas_token.sh 
Please provide the saplib storage account name (SAP_LIBRARY)? mgmtweeusaplib4a1
Please provide the saplib storage account account key (SAP_LIBRARY)? tXcxdh4JbgVYQe3u3uVh88Zu69pbsuxsBfGiXVV85iIEcTchPKw3yRGlTdelmb5KpAyy7N/m4KPurfD8ExYIRA==
Please provide the Deployer keyvault name? MGMTWEEUDEP00userE43

**Comment by hdamecharla** [comment]
Hi @mimergel, thank you for raising the issue. This should be fixed as part of commit b40b4208f5fc827d423d7c4b637d50bece28f344. Kindly re-open the issue if the issue still persists.

Hi @enterprise-1701-d, thanks for suggesting the workaround. I removed your storage account accesskey from the comment. 
🚨  Could you recycle your storage account access keys, please.

**Comment by mimergel** [comment]
unfortunately I got the error again yesterday
