### ISSUE TITLE
[BUG] private ips not working properly

### ISSUE THREAD

**Issue by Klaas-** [Azure/sap-automation#77]
**Describe the bug**
Hi,
if you do not set a private ip you'll currently fall back on a behavior with cidrhost:
https://github.com/Azure/sap-automation/blob/main/deploy/terraform/terraform-units/modules/sap_system/hdb_node/vm-hdb.tf#L26-L31
The right behavior would be to just use dynamic: https://github.com/hashicorp/terraform-provider-azurerm/pull/15264

**Comment by hdamecharla** [comment]
Fixed in #276
