### ISSUE TITLE
Binary download to SCS vm fails msg": "/mnt/resource directory does not exist

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#8]
**Is your feature request related to a problem? Please describe.**
When the pipeline for BOM processing is started after a deallocation it will fail as /mnt/resource will vanish with the deallocation

**Describe the solution you'd like**
Create the temp donwload folder  /mnt/resource in the bom processing pipeline if it doesn't exist

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by PankajMeshramCSA** [comment]
@mimergel  - One more for you, Sir :) 

Please check and close :)

**Comment by mimergel** [comment]
checked and closed.
Thanks
