### ISSUE TITLE
[BUG]An error occurred while loading the YAML build pipeline. Variable group was not found or is not authorized for use

### ISSUE THREAD

**Issue by sapddic** [Azure/sap-automation#89]
**Describe the bug**

An error occurred while loading the YAML build pipeline. **Variable group  was not found or is not authorized for use**. For authorization details, refer to https://aka.ms/yamlauthz.

Permissions unrestricted /open for the pipeline and linked to the pipeline as well
Variable group linked in the trigger section as well.
[pipelinebug.docx](https://github.com/Azure/sap-automation/files/8074058/pipelinebug.docx)

**To reproduce**

**Expected behavior**

**Additional context**

**Comment by KimForss** [comment]
@sapddic is this still an issue for you?

**Comment by hdamecharla** [comment]
The steps to configure pipelines and variable groups are defined in the following document [Configure DevOps](https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-configure-devops?tabs=windows)
