### ISSUE TITLE
[BUG] Invalid value for "inputMap" parameter: the given object has no attribute "Optimized"

### ISSUE THREAD

**Issue by RSteeno** [Azure/sap-automation#92]
**Describe the bug**
I'm following the [DevOps hands-on-lab](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-devops-tutorial) and am using the **samples/WORKSPACES/SYSTEM/DEV-WEEU-SAP01-X00** sample configuration.

Provisioning of control plane and Workload zone through ADO pipelines successfully completed.

When executing the **03-sap-system-deployment.yml** pipeline from Azure DevOps the following error is thrown.

```
#########################################################################################
#                                                                                       #
#                             Running Terraform plan                                    #
#                                                                                       #
#########################################################################################


Error: Invalid function argument

  on ../../terraform-units/modules/sap_system/app_tier/variables_local.tf line 312, in locals:
 312:   app_sizing = lookup(local.sizes.app, local.vm_sizing)
    ├────────────────
    │ local.sizes.app is object with 2 attributes

Invalid value for "inputMap" parameter: the given object has no attribute
"Optimized".

Error: Invalid function argument

  on ../../terraform-units/modules/sap_system/app_tier/variables_local.tf line 314, in locals:
 314:   scs_sizing = lookup(local.sizes.scs, local.vm_sizing)
    ├────────────────
    │ local.sizes.scs is object with 2 attributes

Invalid value for "inputMap" parameter: the given object has no attribute
"Optimized".

Error: Invalid function argument

  on ../../terraform-units/modules/sap_system/app_tier/variables_local.tf line 316, in locals:
 316:   web_sizing = lookup(local.sizes.web, local.vm_sizing)
    ├────────────────
    │ local.sizes.web is object with 2 attributes

Invalid value for "inputMap" parameter: the given object has no attribute
"Optimized".

```
After some investigation, found that the file **/deploy/configs/app_sizes.json** does NOT contain an Optimized property for the app tier, _Default_ and _Production_ are the only two options.

To resolve I've made the following update to the tfvars file.  

![image](https://user-images.githubusercontent.com/9053423/154365037-737b885b-17c9-40e9-bb94-32c1cc053201.png)

**To reproduce**
1. Setup ADO project
2. Follow instructions https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-devops-tutorial to deploy the Control Plane, Workload Zone and finally the SAP System step.

**Expected behavior**
The environment should be successfully provisioned.

**Additional context**

**Comment by RSteeno** [comment]
After checking the private-preview branch, the ```/deploy/configs/app_sizes.json``` does have the **Optimized** property map for the app, scs and web tiers.

I've also noticed that in the ```10-remover-terraform.yaml``` pipeline in the master branch, there are ```git pull``` commands that cause the pipeline to fail. These commands are not in the master branch.

For our testing of the DevOps pipelines, should we be using the private-review branch?  

I was going to create a fork and update these file, but since they are in the private-preview branch I didn't.

**Comment by KimForss** [comment]
Hi

We have "soft released" the pipelines and the supporting playbooks, I would recommend using the main branch for testing as it should be the most stable. 

Optimized is also in the maiin branch now so am closing this issue.
