### ISSUE TITLE
Update configure.sh to parameterize the repo to use

### ISSUE THREAD

**Issue by RSteeno** [Azure/sap-automation#94]
**Is your feature request related to a problem? Please describe.**

When the Control Plane is deployed, the ```configure_deloyer.sh ``` is hardcoded to clone the github repo.

```
# Azure SAP Automated Deployment directories
asad_home="${HOME}/Azure_SAP_Automated_Deployment"
asad_ws="${asad_home}/WORKSPACES"
asad_repo="https://github.com/Azure/sap-automation.git"
asad_dir="${asad_home}/$(basename ${asad_repo} .git)"
```

**Describe the solution you'd like**
Update the ```configure_deloyer.sh``` script to use a variable for the repo.  When using ADO, this value should be set from the **Repository** variable defined in the SDAF-General varable group.

**Describe alternatives you've considered**
Current workaround is to manually replace the sap-automation repo on the deployer with the desired repo.

**Additional context**
n/a

**Comment by hdamecharla** [comment]
@RSteeno , thank you for raising an enhancement/feature request. 

This is added as part of PR #304 and further enhanced in commit [f2ff6e3](https://github.com/Azure/sap-automation@f2ff6e35ec18e352887797221bf7f24ec06a54cf).
