### ISSUE TITLE
Control Plane deployment crash with no access to Key Vault

### ISSUE THREAD

**Issue by iwalker2000** [Azure/sap-automation#97]
**Describe the bug**
Region prep script is crashing with following errors:
odule.sap_deployer.azurerm_key_vault.kv_user[0]: Still creating... [40s elapsed]
module.sap_deployer.azurerm_key_vault.kv_user[0]: Still creating... [50s elapsed]
module.sap_deployer.azurerm_key_vault.kv_user[0]: Still creating... [1m0s elapsed]
module.sap_deployer.azurerm_key_vault.kv_user[0]: Still creating... [1m10s elapsed]
module.sap_deployer.azurerm_key_vault.kv_user[0]: Still creating... [1m20s elapsed]
module.sap_deployer.azurerm_key_vault.kv_user[0]: Still creating... [1m30s elapsed]
module.sap_deployer.azurerm_key_vault.kv_user[0]: Still creating... [1m40s elapsed]
module.sap_deployer.azurerm_key_vault.kv_user[0]: Still creating... [1m50s elapsed]
module.sap_deployer.azurerm_key_vault.kv_user[0]: Still creating... [2m0s elapsed]
module.sap_deployer.azurerm_key_vault.kv_user[0]: Still creating... [2m10s elapsed]
module.sap_deployer.azurerm_key_vault.kv_user[0]: Creation complete after 2m11s [id=/subscriptions/1d032958-7678-44b8-82ad-3cd6fdb1f9a9/resourceGroups/SAP-AFCP-TEST/providers/Microsoft.KeyVault/vaults/MGMTWEEUDEP00user1A2]
module.sap_deployer.azurerm_key_vault_access_policy.kv_user_msi[0]: Creating...
module.sap_deployer.azurerm_key_vault_access_policy.kv_user_pre_deployer[0]: Creating...
module.sap_deployer.azurerm_key_vault_access_policy.kv_user_pre_deployer[0]: Creation complete after 9s [id=/subscriptions/1d032958-7678-44b8-82ad-3cd6fdb1f9a9/resourceGroups/SAP-AFCP-TEST/providers/Microsoft.KeyVault/vaults/MGMTWEEUDEP00user1A2/objectId/70000000-0000-0000-0000-000000000000]
module.sap_deployer.azurerm_key_vault_access_policy.kv_user_msi[0]: Still creating... [10s elapsed]
module.sap_deployer.azurerm_key_vault_access_policy.kv_user_msi[0]: Creation complete after 17s [id=/subscriptions/1d032958-7678-44b8-82ad-3cd6fdb1f9a9/resourceGroups/SAP-AFCP-TEST/providers/Microsoft.KeyVault/vaults/MGMTWEEUDEP00user1A2/objectId/c9e19a85-c394-4fc4-965d-eabfe715ae62]
module.sap_deployer.azurerm_key_vault_secret.username[0]: Creating...
module.sap_deployer.azurerm_key_vault_secret.pk[0]: Creating...
module.sap_deployer.azurerm_key_vault_secret.ppk[0]: Creating...
╷
│ Error: checking for presence of existing Secret "SAP-AFCP-TEST-sshkey" (Key Vault "https://mgmtweeudep00user1a2.vault.azure.net/"): keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error:autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=b677c290-cf4b-4a8e-a60e-91ba650a4abe;oid=ea425602-a18d-4912-9375-78ee23dc2bac;numgroups=1;iss=https://sts.windows.net/1f6c67d4-7e4c-4119-8ad9-435710ee4b29/' does not have secrets get permission on key vault 'MGMTWEEUDEP00user1A2;location=westeurope'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287"InnerError={"code":"AccessDenied"}
│
│   with module.sap_deployer.azurerm_key_vault_secret.ppk[0],
│   on ../../terraform-units/modules/sap_deployer/key_vault.tf line 168, in resource "azurerm_key_vault_secret" "ppk":
│  168: resource "azurerm_key_vault_secret" "ppk" {
│
╵
╷
│ Error: checking for presence of existing Secret "SAP-AFCP-TEST-sshkey-pub" (Key Vault "https://mgmtweeudep00user1a2.vault.azure.net/"): keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=b677c290-cf4b-4a8e-a60e-91ba650a4abe;oid=ea425602-a18d-4912-9375-78ee23dc2bac;numgroups=1;iss=https://sts.windows.net/1f6c67d4-7e4c-4119-8ad9-435710ee4b29/' does not have secrets get permission on key vault 'MGMTWEEUDEP00user1A2;location=westeurope'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}
│
│   with module.sap_deployer.azurerm_key_vault_secret.pk[0],
│   on ../../terraform-units/modules/sap_deployer/key_vault.tf line 179, in resource "azurerm_key_vault_secret" "pk":
│  179: resource "azurerm_key_vault_secret" "pk" {
│
╵
╷
│ Error: checking for presence of existing Secret "SAP-AFCP-TEST-username" (Key Vault "https://mgmtweeudep00user1a2.vault.azure.net/"): keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=b677c290-cf4b-4a8e-a60e-91ba650a4abe;oid=ea425602-a18d-4912-9375-78ee23dc2bac;numgroups=1;iss=https://sts.windows.net/1f6c67d4-7e4c-4119-8ad9-435710ee4b29/' does not have secrets get permission on key vault 'MGMTWEEUDEP00user1A2;location=westeurope'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}
│
│   with module.sap_deployer.azurerm_key_vault_secret.username[0],
│   on ../../terraform-units/modules/sap_deployer/key_vault.tf line 190, in resource "azurerm_key_vault_secret" "username":
│  190: resource "azurerm_key_vault_secret" "username" {
│
╵

**To reproduce**
just run hands-on lab commands as on https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-tutorial - Deploy control plane, step 1's script

**Expected behavior**
Deploy region as expected

**Additional context**
Tested on 3 different environments/6 regions with same error
error says that my user account has no permissions to have the access to KV but scripts is ran with SPN as parameter (should it be SPN app_id there?).

**Comment by KimForss** [comment]
Hi, sorry to hear this.

Are you running this from Cloud shell? 

Have you tried to run az logout and then az login so that you are logged on as you and not the cloudshell managed ID?

**Comment by iwalker2000** [comment]
> 

Yes, I tried to do troubleshooting as it is recommended in documentation - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-tutorial - "If you run into authentication issues, run az logout to log out and clear the token-cache, then run az login to reauthenticate." 

What account have I to use for that az login? It is not clear in documentation what credentials have to be used.

**Comment by mkdeegan** [comment]
Has this been resolved?
On initial Control Plane Deployment from the Cloud Shell the credentials that are used are your own credentials, and you must have "Contributor with Authorization or Owner" RBAC for the subscription.

**Comment by jkirkmannz** [comment]
Still getting the error, having tried with two different accounts/tenancies/subscriptions. Running from CloudShell and owner role in both cases.

**Comment by sapien47** [comment]
@jkirkmannz : Thanks for the tip, worked for me

**Comment by PankajMeshramCSA** [comment]
@iwalker2000  - I see this issue is resolved, I am closing this issue.
