### ISSUE TITLE
[BUG] HANA Installation fails with "error while evaluating conditional (hana_installation.rc > 0): 'dict object' has no attribute 'rc'""

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-automation#99]
**Describe the bug**
HANA Installation fails
fatal: [x00dhdb00l0e6]: FAILED! => {
2022-02-24T10:40:54.8461013Z     "msg": "The conditional check 'hana_installation.rc > 0' failed. The error was: error while evaluating conditional (hana_installation.rc > 0): 'dict object' has no attribute 'rc'"

**To reproduce**
Run Pipeline 5 and install HANA (was using Azure DevOps)

**Expected behavior**
no error

**Additional context**
n.a.

**Comment by KimForss** [comment]
Which distro is causing this?

The error is strange as the .rc property is (should be) present whenever you register a variable when using either ansible.builtin.shell or ansible.builtin.command.

**Comment by mimergel** [comment]
Thanks for solving the problem. let's close it.
